### ISSUE TITLE
toast fades away immediately after a hover-off

### ISSUE THREAD

**Issue by johnpapa** [CodeSeven/toastr#11]
I added a new feature to keep the toast around after hover-off for an extended 1 second (customizable). The option is called extendedTimeOut

**Comment by dgoncalves1** [comment]
Know its old, but is it possible to set it to not fade out when you hover?

**Comment by TimFerrell** [comment]
What do you want it to do if not fade? Close immediately? Not close?

**Comment by dgoncalves1** [comment]
Sorry i made a mistake, i want the toastr to remain there (sticky) even if you hover it.
