### ISSUE TITLE
Timing issue with clear() function

### ISSUE THREAD

**Issue by knunery** [CodeSeven/toastr#118]
There is a timing issue with toastr.clear().

Got to http://codeseven.github.io/toastr/demo.html.
Open a console in Chrome.

run the following command twice

> toastr.clear(); toastr.success("blah");

You should see "blah" displayed twice but you don't in my testing.  The second run is clearing the second blah which looks like a timing bug with the clear function.

**Comment by jamespsterling** [comment]
I have a scenario when I'm switching UI Routes and would like to be able to dismiss toasts immediately. What about .clear({force: true}) to do something like that, rather than waiting for the timeout?
