### ISSUE TITLE
function clear($toastElement) takes wrong hideDuration option

### ISSUE THREAD

**Issue by CloudCees** [CodeSeven/toastr#120]
Hello,

"toastr.clear($toastElement)" hides element with the 'default' duration, not with the duration given in the options of that toast instance:

``` javascript
             var $toast = toastr['info']('You are invited by ' + invite.displayName + '.', 'Invite', {
                hideDuration: 100,
                timeOut: 0,
                extendedTimeOut: 0
            });
```

So, when closing the toast instance with:

``` javascript
toastr.clear($toast);
```

It does not closes the toast with a duration of 100 but with the duration declared in the default options. Is this by design?

**Comment by maxyharr** [comment]
Is there a way to override this?
