### ISSUE TITLE
toastr.options.positionClass not refreshing

### ISSUE THREAD

**Issue by simonmlewis** [CodeSeven/toastr#131]
Hi,

This is happening in both my code and also on the example page:
http://codeseven.github.io/toastr/demo.html

If I use say top right and show toast, then change to bottom right and show toast, the toast gets displayed in the top right still.

We are trying to get a convention in place by where errors are top right and warnings bottom right but at the moment we can't get the position class to refresh.

Any ideas?

**Comment by TimFerrell** [comment]
The toastr container is set when the first toast is fired, and will hold its positioning until the all toasts are cleared from the container.
After all toasts are cleared, it can move around however you'd like. If you'd like, you can anchor the container to different elements to get the functionality you're seeking.
