### ISSUE TITLE
How to clear toasts before showing a new toast?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [CodeSeven/toastr#149]
I have the following code that I use to show the errors as a bottom full-width

```
toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-bottom-full-width",
            "onclick": null,
            "showDuration": "1000",
            "hideDuration": "0",
            "timeOut": "0",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
toastr.error(message, title);
```

I am trying to clear all the previous `toastr` message before I call this again. How can I do that?

Calling `toastr.clear()`, before setting the options, breaks the options.

Example: http://cssdeck.com/labs/wbzeauxe

**Comment by jeremyasm** [comment]
![image](https://user-images.githubusercontent.com/11631239/44977083-9cc7d880-af99-11e8-881c-9dc1698d106c.png)

**Comment by SelvakumarMahalingam** [comment]
Thank you jeremyasm

**Comment by danielmoreirabiscai** [comment]
fsdsfdsfdsfd

**Comment by aamirrajpot** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/11631239/44977083-9cc7d880-af99-11e8-881c-9dc1698d106c.png)

where to add this code ??
Please explain a little bit

**Comment by naveedshahji** [comment]
@aamirrajpot add it in appmodule like imports: [ ToastrModule.forRoot({maxOpened: 1}),]

**Comment by DeliaMaciasUrzua** [comment]
![image](https://user-images.githubusercontent.com/102176769/176315396-bfa5b0ea-e20a-483f-ab02-25074bd79bd8.png)


and next i create a service like this..
![image](https://user-images.githubusercontent.com/102176769/176315509-b80c47b9-9b30-4c8d-aa16-12d2fba10fe3.png)
