### ISSUE TITLE
Is it possible to not auto hide the toastr?

### ISSUE THREAD

**Issue by germanger** [CodeSeven/toastr#166]
I want the toastr to stay there until the user clicks the toastr's close icon. Is it possible to setup hideDuration (or other parameter) to achieve this?

Also I should mention that it is not very clear in the documentation what means each of the options regarding durations.

showDuration
hideDuration
timeOut
extendedTimeOut

Beside this, I really like this toastr widget.

**Comment by Akbarics** [comment]
Prevent close Toastr on Click by this code:
$.fn.noop = function () { return this; };
toastr.options.hideMethod = 'noop';

**Comment by jdnichollsc** [comment]
Thanks @johnpapa! 👍

**Comment by CallMeChero** [comment]
Yes it's possible. @johnpapa was right.  Toastr will only close after clicking "X". Just set options like this:
closeButton: true,
extendedTimeOut: 0,
timeOut: 0,
tapToDismiss: false

**Comment by neobie** [comment]
how to apply option to specific toast only ?
