### ISSUE TITLE
tapToDismiss ignored when onclick is set

### ISSUE THREAD

**Issue by RiCKe** [CodeSeven/toastr#171]
Hello, 

I'm trying to display a toast with the property tapToDismiss set to false
```javascript
toastr.info('title', 'message', {
tapToDismiss: false, 
closeButton: true, 
timeOut: 0, 
extendedTimeOut: 0, 
});
```
This works well but if I add a onclick handler, the toast closes when I click it.
```javascript
toastr.info('title', 'message', {
tapToDismiss: false, 
closeButton: true, 
timeOut: 0, 
extendedTimeOut: 0, 
onclick: function(){
    alert('click');
}
});
```

Currently, I've found a workaround by adding the click handler on the elem returned by the info method but I think there is a little bug here...
```javascript
var toast = toastr.info('title', 'message', {
tapToDismiss: false, 
closeButton: true, 
timeOut: 0, 
extendedTimeOut: 0, 
});
toast.on('click', function(){
    alert('click');
});
```
Thanks

**Comment by bs-thomas** [comment]
Interesting that the issue is opened for 2 years, and is not resolved still.  Hmmm...

**Comment by TimFerrell** [comment]
@bs-thomas if you'd to contribute to resolving this, then please do so and open a pull request.

**Comment by TimFerrell** [comment]
Thanks @TKP-777!

**Comment by raquelrocha** [comment]
I'm having this problem again, and i've checked toastr.js and somehow the change made here no longer exists:
```
if (options.onclick) {
   $toastElement.click(function (event) {
           options.onclick(event);
           hideToast();
    });
}
```

If it is meant to be this way, then please guide me to a workaround to this behavior.
