### ISSUE TITLE
Shouldn't shown and hidden callbacks be a per-toastr setting?

### ISSUE THREAD

**Issue by eappell** [CodeSeven/toastr#185]
I use toastr's all over a large project I am working on.  In most cases, I need to do some action after the toastr is shown or hidden, to provide the asynchronous behavior I need to achieve (i.e. SHOW the toastr, then DO SOMETHING).  In every case I can find the action is linked to the specific toastr I am displaying, and should NOT be a global option.  So to avoid other issues on the page/view, I have to setup every toastr onShown or onHidden function this way:

``` javascript
toastr.options.onShown = function(){
    toastr.options.onShown = null;
    // DO SOME STUFF HERE
};
toastr.success('Yay, you did it!');
```

Shouldn't there be an option to provide an onShown within each toastr instance, so that it is not a global setting for all toastr's?  Or maybe I'm missing the whole point (quite possible)?

**Comment by simonbook** [comment]
Do we have a per toast callback yet?

**Comment by knownasilya** [comment]
Could we just send the affected toast as an argument?

**Comment by aeciolevy-ven** [comment]
Was it addressed?

**Comment by eappell** [comment]
Honestly I don't remember - it was over 5 years ago...  I think so.

**Comment by aeciolevy-ven** [comment]
Well, anyway just an idea you can add this to the global options and after calling the `toastr` be called revert the option back to default.
