### ISSUE TITLE
Set different timeouts based on toast type

### ISSUE THREAD

**Issue by judowalker** [CodeSeven/toastr#203]
Would it be possible to set different timeouts based on toast type. For example I want error toasts to be sticky because I want to ensure that the user sees these toasts and has to manually close them.

**Comment by victornpb** [comment]
This is the solution I could came up
    toastr.options = {
        newestOnTop      : true,
        closeButton      : false,
        progressBar      : true,
        preventDuplicates: false,
        showMethod       : 'slideDown',
        timeOut          : 10000, //default timeout,

        timeOutError: 0,
    };
    
    /** Force toastr.error to be sticky */
    toastr.error_ = toastr.error;
    toastr.error = function(a,b,c){
        var t = toastr.options.timeOut;
        toastr.options.timeOut = 0;
        toastr.error_(a,b,c);
        toastr.options.timeOut = t;
    };

**Comment by kinetiq** [comment]
Worked for me, although I also had to explicitly set extendedTimeOut to prevent error messages from disappearing after hover.

**Comment by muhammad-qadeerr** [comment]
$(document).ready(function () {
    /** Force toastr.info to be dissappear after 5 sec */
    toastr.info_ = toastr.info;
    toastr.info = function (a, b, c) {
        var t = toastr.options.timeOut;
        toastr.options.timeOut = 5000;
        toastr.info_(a, b, c);
        toastr.options.timeOut = t;
    };
});


I am trying to make info time toastr to dissappear after 5 sec, it didn't worked for me.
