### ISSUE TITLE
Resolve jshint issues

### ISSUE THREAD

**Issue by TimFerrell** [CodeSeven/toastr#206]

**Comment by ctesniere** [comment]
Hi,
with the error `['success'] is better written in dot notation.` of jshint,
the solution is written : `toastr.success('foo');` is no `toastr['success']('foo');`

**Comment by ShashankaNataraj** [comment]
Is anyone going to work on this or can I take this up?

**Comment by TimFerrell** [comment]
I'd love to look at a PR for this if you're infestered in taking a look.

**Comment by ShashankaNataraj** [comment]
Sure will do :) I will make a PR and submit for your review.

**Comment by TimFerrell** [comment]
@ShashankaNataraj - any update?

**Comment by TimFerrell** [comment]
Resolved in develop with https://github.com/CodeSeven/toastr/commit/c4fba3827038a1cfefaec26bea31044e7042e010.
