### ISSUE TITLE
For the love of Angular, get rid of jQuery... please?

### ISSUE THREAD

**Issue by mdelgadov** [CodeSeven/toastr#217]
I learned angular with your Pluralsight course... thanks.
Now to business, is there a way to get rid of jQuery (nothing against it,just not the angular way).

Thanks...

Big Fan

**Comment by TravisTX** [comment]
I'd love to assist with v3.  Is discussion / planning happening elsewhere, or is this it?

**Comment by TimFerrell** [comment]
We've had some offline discussion regarding v3, mostly in regards to design specs, not so much code. I'll try my best to get those up into Github shortly.

**Comment by TimFerrell** [comment]
Merged in our discussions into the readme on the [v3 branch](https://github.com/CodeSeven/toastr/tree/v3).

Still need to clean up existing code, etc.

**Comment by johnpapa** [comment]
Let's not comit directly to the v3 branch, but instead through feature branches off of it.

**Comment by TimFerrell** [comment]
Agreed - just wanted to get the branch to a good starting place first.

**Comment by johnpapa** [comment]
Yep, no worries.

Also .. not sure if it has to be a directive for angular. toastr, first, should be on its own without angular or jquery. then, we can also aim at toastr working with angular, react, and other libraries.

**Comment by TimFerrell** [comment]
That was my thinking, and I left the angular specification out of the design spec for that reason. 

In terms of modularity, should the native toastr module even include angular? Or should we create a second file that references the ES6 module and implements it however necessary? I'm thinking the later.

**Comment by TimFerrell** [comment]
Also, I just created the v3 label for issues relating to the v3 build. I'm thinking we can use it for bugs that we either too minor/major for the 2.x release, and feature changes that would've been too disruptive. 

By tagging, I'm hopping we won't lose sight of those things.

**Comment by TimFerrell** [comment]
I played around with ES6 a little bit earlier today, does anyone know of a good reference architecture for modules or can recommend a best practices document?

Also, I've got some ideas regarding animation that I've been doing some research into. I'd like to take on that piece if no one has any objections.

**Comment by johnpapa** [comment]
- v3 tag - yes, good idea.
- animations - go for it.
- es6 modules - nothing magical. we can talk
- confused on this ... "In terms of modularity, should the native toastr module even include angular? Or should we create a second file that references the ES6 module and implements it however necessary? I'm thinking the later." No angular should exist in toastr at all. We'll make an angular plugin in a new repo.

**Comment by TimFerrell** [comment]
Great.

**Comment by leschirmeur** [comment]
If you come up with an angular plugin, shouldn't it be rather a service than a directive?

**Comment by nevf** [comment]
+1 for losing jQuery. I find http://youmightnotneedjquery.com/ very helpful. 

If you still need jQuery a new lighter weight implementation you could look at is https://github.com/bendc/sprint It is missing a few jQuery functions including extend().

**Comment by TimFerrell** [comment]
@nevf  - This is a work in progress.

See (and potentially contribute) here: https://github.com/CodeSeven/toastr/tree/v3

**Comment by prawirapasek** [comment]
i have same problem :(

**Comment by ibc** [comment]
>
* `document.getElementById`
* `document.getElementsByClassName` (not supported in <= IE8)

Please move to `element.querySelector(selector)` where `selector` is the same as a jQuery selector.

https://developer.mozilla.org/es/docs/Web/API/Element/querySelector

**Comment by TimFerrell** [comment]
@ibc if you're interested in contributing to v3 please checkout the v3 branch.

**Comment by TimFerrell** [comment]
@ShashankaNataraj  - might be able to use your help in getting the gulp tests running from CLI. Care to check out the v3 branch and give things a shot? 

Seems like you've been pretty active on the project lately.

**Comment by ShashankaNataraj** [comment]
@TimFerrell Would love to give this a shot! Thanks for pointing me to this thread! Will start hacking on this.

**Comment by JeremyCarlsten** [comment]
Where are you at on V3 and or the angular repo? 
I found this https://github.com/jirikavi/AngularJS-Toaster

but I would rather see an official toastr release for my own sanity. 

Let me know if you need assistance.

**Comment by TimFerrell** [comment]
Updates were pushed to the v3 branch last night. Please take a look and contribute!

**Comment by alexsilveira** [comment]
Hello!

 

New message, please read <http://apc-ups.dk/aware.php?rm>

 

alexsilveira@ig.com.br

**Comment by TimFerrell** [comment]
jQuery will no longer be a dependency in v3, but will remain in 2.x.
