### ISSUE TITLE
Remove toast explicitly even on focus

### ISSUE THREAD

**Issue by jstawski** [CodeSeven/toastr#220]
Looking at the [source code](https://github.com/CodeSeven/toastr/blob/master/toastr.js#L111) the toast doesn't get removed if there is focus on an element. I imagine that was done so the toast wouldn't get cleared automatically by the timer if you are working on it. 

Shouldn't we allow the removal of the toast if we explicit call the remove? After all I am the developer and I know what I'm doing.

By the way the same thing happens with `clear`

**Comment by TimFerrell** [comment]
Closing because PR was merged.
