### ISSUE TITLE
Close button needs line-height: 1

### ISSUE THREAD

**Issue by judowalker** [CodeSeven/toastr#222]
The Close button needs `line-height: 1` so that it doesn't inherit the line-height and affect the size of the toast and the vertical alignment. Bootstrap 3 sets `line-height: inherit` on `button` which means the Close button's line-height can change. Your demo page uses Bootstrap 2.3.1 which sets `line-height: 20px` on `button`.

**Comment by TimFerrell** [comment]
@pickledyamsman - can you take a look here?

**Comment by TimFerrell** [comment]
Resolved via PR #437. Thanks @pickledyamsman!
