### ISSUE TITLE
Ensuring that Scripts are not injected into the page

### ISSUE THREAD

**Issue by rohit-lakhanpal** [CodeSeven/toastr#231]
Whilst running a security audit noticed that when a script is passed to toastr in the message or title params, it executes it instead of displaying it. 

Here is an example. http://run.plnkr.co/ZFgim3Ls8lLjPOu4/

I have added the following pull request to combat the issue.

https://github.com/CodeSeven/toastr/pull/227

**Comment by TimFerrell** [comment]
HTML escaping has been added in 2.1.2.
