### ISSUE TITLE
"toast-center-center" position?

### ISSUE THREAD

**Issue by mcmegavolt** [CodeSeven/toastr#233]
May you provide such class for positioning in the center of page?

**Comment by johnpapa** [comment]
this has been requested, but its not on our radar. all pul requests have been situational, meaning they only work in certain circumstances, but not all. would only pull if it was foolproof. otherwise my advice is to add your own

**Comment by xcartmods** [comment]
```
.toast-center-left { left: 10px; top: 50%; right: 10px; transform: translate(0px, -50%); }
.toast-center-center { top: 50%; left: 50%; transform: translate(-50%, -50%); }
.toast-center-right { right: 10px; top: 50%; transform: translate(0px, -50%); }
```

**Comment by jbinnig** [comment]
.toast-center-center {
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translateX(-50%) translateY(-50%);
  -webkit-transform: translate(-50%,-50%);
  transform: translate(-50%,-50%);
}
