### ISSUE TITLE
Bower version ?

### ISSUE THREAD

**Issue by phmatray** [CodeSeven/toastr#234]
Is bower version of Toastr  is up to date?
I've version 2.1.0 but I don't see preventDuplicates and progressBar in src.
After investigations, Bower version in bower.json file is 2.1.0 BUT toastr.js file is in 2.0.3.

**Comment by robertd** [comment]
@phmatray I'm getting the latest version of toastr. Try cleaning your bower cache with `bower cache clean`. It happens all the time to me on win box.

**Comment by johnpapa** [comment]
i just verified the toastr.js files here and in the bower repo are 2.1.0
