### ISSUE TITLE
Is it possible to capture a toast(r) instance?

### ISSUE THREAD

**Issue by robertd** [CodeSeven/toastr#236]
Is there a way to capture an instance of a toastr and change messages/title/type. Something like this: "Searching..." (info color) -> ajax call 5 sec later -> "Found 10 results" (success color) on a single toastr notification box.

Thanks!

**Comment by johnpapa** [comment]
sure. toastr returns the jquery object so grab it and change it how you like

**Comment by robertd** [comment]
Is there an example I can use as a guide?

—

**Comment by robertd** [comment]
I saw #190 but I was wondering if there is a more elegant solution than using jQuery.
