### ISSUE TITLE
toastR OnHover

### ISSUE THREAD

**Issue by ChadSTT** [CodeSeven/toastr#239]
Can you guys please make a setting available that allows you to chose if the popup disappear on hover or on click,
Currently you need set the display time to force the onhover to not work.
This is inconvenient, I want it to stay up for x duration and only disappear once the popup has been clicked.

**Comment by sromovskypeter** [comment]
Hello, I have a similar problem.
I dont want my notification to react on hover. If i set extendedTimeOut to 0, notification disappear immediately after mouseout. I want to keep timeOut countdown even after hover.
Is that possible? 
Thank you for answer.

**Comment by TimFerrell** [comment]
I'd be interested in reviewing a pull request (against the develop branch) if either of you would like to implement this.
Core things that'd need to be satisfied:

- No breaking changes
- Functionality is toggled by a property on the options object

**Comment by johnpapa** [comment]
And unit tests :)

**Comment by TimFerrell** [comment]
@sromovskypeter - setting the extendedTimeOut to 0 should keep the toast alive indefinitely.

**Comment by TimFerrell** [comment]
@sromovskypeter - any update?

**Comment by grantiverson** [comment]
@TimFerrell It seems to me that the original feature request is available. Setting `closeOnHover` to `false` produces toasts that are not affected by extendedTimeOut

Here's an example: https://codepen.io/grantiverson/pen/Nzgqxx

**Comment by TimFerrell** [comment]
Perfect, thanks @grantiverson! Closing.
