### ISSUE TITLE
Latest commit to gh-pages reverted #230

### ISSUE THREAD

**Issue by robertd** [CodeSeven/toastr#242]
Latest [commit](d6903a37de88ebc21e171d26289cf64fb88c89a0) reverted changes introduced in #230 and as a result `toastr[success]("My name is Inigo Montoya. You killed my father. Prepare to die!")` is trowing again ` Uncaught ReferenceError: success is not defined`.

Thanks

**Comment by johnpapa** [comment]
Needs quotes. Wanna PR?

**Comment by robertd** [comment]
Sure

**Comment by robertd** [comment]
Done
