### ISSUE TITLE
 toastr.clear($toast, { force: true }) not in version 2.1.0?

### ISSUE THREAD

**Issue by jedwards1211** [CodeSeven/toastr#243]
Hi all,

This is a great project!
But I wanted to say I had quite a headache trying to mimic the behavior of "Add button to force clearing a toast, ignoring focus" from your example site, because it wasn't until I dug deep down into the code that I realized the toastr.js 2.1.0 that I got from npm doesn't support the force option like the toastr.js on the example site does.

So I'm assuming the example site uses pre-release code?  If so it might cause new users fewer headaches if make the site use only the current release.

Thanks!
Andy

**Comment by TimFerrell** [comment]
Hey @jedwards1211 - thanks for the input, that's good feedback.

You're correct in your understanding that the demo and repo includes code that hasn't been pushed out to the CDNs yet. 

We'll look into ways to make this a bit clearer in the future.

**Comment by jedwards1211** [comment]
Thanks for taking the time to read it.

-Andy


On Sat, Jan 31, 2015, at 11:30 AM, Tim Ferrell wrote:
> Hey @jedwards1211[1] - thanks for the input, that's good feedback.


> You're correct in your understanding that the demo and repo includes
> code that hasn't been pushed out to the CDNs yet.


> We'll look into ways to make this a bit clearer in the future.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/jedwards1211
  2. https://github.com/CodeSeven/toastr/issues/243#issuecomment-72327117
