### ISSUE TITLE
I get toastr.min.js not found (failed GET request)

### ISSUE THREAD

**Issue by pamanes** [CodeSeven/toastr#244]
It appears that it tries to load the map file from the wrong location, I changed this on the toastr.min.js to fix the issue:

//# sourceMappingURL=/toastr.js.map

to this (removed the slash):

//# sourceMappingURL=toastr.js.map

**Comment by johnpapa** [comment]
Tim ?

**Comment by TimFerrell** [comment]
Resolved as of https://github.com/CodeSeven/toastr/commit/4a51cce85755036e49ae47dc5269672d159824c4 on master.

**Comment by davidchavarri** [comment]
fixed. thnks.
