### ISSUE TITLE
Position not honored if existing toasts are displayed

### ISSUE THREAD

**Issue by pseabury** [CodeSeven/toastr#245]
Even if you pass in overrideOptions with a different position, the toasts will show up using the position of any existing visible toasts.  Looking at the attached image, you can reproduce on the demo page by:

1.)  Keep all default options (top right position) and click "Show Toast" 3 times
2.)  While previous 3 toasts are still visible, Change position to bottom right and click "Show Toast: 3 more times.

Expected result: 3 toasts at top right, 3 toasts at bottom right
Actual result: 6 toasts top right.

![image](https://cloud.githubusercontent.com/assets/1918526/6028842/0a261c92-abb2-11e4-9c74-7b681e227cb0.png)

**Comment by TimFerrell** [comment]
This is actually working as designed. The toastr container doesn't move while it has visible toasts in it. However, if there are no visible toasts then the container will move around. 
Example here: https://vid.me/zOJo

**Comment by pseabury** [comment]
Is there a workaround to get this working as I described?

**Comment by TimFerrell** [comment]
You can clear all of the visible toasts off the screen, which would in turn clear the container and allow it to be repositioned.
