### ISSUE TITLE
Demo needs some quotes

### ISSUE THREAD

**Issue by rapPayne** [CodeSeven/toastr#248]
In http://codeseven.github.io/toastr/demo.html, the code example created says:
    `Command: toastr[error]("Toast MessageBody", "Toast Title")`
... when it should say ...
    `Command: toastr["error"]("Toast MessageBody", "Toast Title")`

We just need single or double quotes around the toast type.

**Comment by johnpapa** [comment]
yep, not the code but the output. wanna make a PR on the demo?

**Comment by TimFerrell** [comment]
Resolved.
