### ISSUE TITLE
Show message until I close them manually

### ISSUE THREAD

**Issue by squadwuschel** [CodeSeven/toastr#252]
Hi, is it possible to show error Messages until I dissmiss them so that they don't go away alone and all other message Types work "noramlly" and hide after the timeout?

**Comment by TimFerrell** [comment]
You can set a timeout specific to the toast you created with a high timeout value using the `options` property. This will allow that one toast to stick around while all others would disappear at the default intervals.

**Comment by flyfishMT** [comment]
How would you then close a specific instance manually?

**Comment by TimFerrell** [comment]
If you mean programmatically, this is one way:

```
var x = toastr.success("Test","Great");
    setTimeout(function () {
	    $(x).hide();
    },2000);
```

**Comment by flyfishMT** [comment]
I re-read the original question and I guess I'm a little off-topic so sorry about that, but I meant, I want to close it myself. Like this: 

    var handle = toastr.success("Test","Great", {timeout: NEVER}); 
    //...
    handle.closeToast();
