### ISSUE TITLE
Manipulating Toastr instance demo

### ISSUE THREAD

**Issue by robertd** [CodeSeven/toastr#255]
I'm posting this here for other people who might need the same functionality.

Related to #236 & following twitter conversation

<blockquote class="twitter-tweet" data-conversation="none" lang="en"><p><a href="https://twitter.com/ferrell_tim">@ferrell_tim</a> <a href="https://twitter.com/John_Papa">@John_Papa</a> Ahhh I see. I was expecting something along the lines of t.setText() t.setTimeout(), t.setOptions().. etc.Sweet. Thx</p>&mdash; R2D2 (@robertR2D2) <a href="https://twitter.com/robertR2D2/status/558091703199227906">January 22, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Example can be found here.
https://gist.github.com/robertd/b00979aef4454217737d

Cheers!

**Comment by TimFerrell** [comment]
Thanks for the information capture, @robertd!
