### ISSUE TITLE
Set width programmatically

### ISSUE THREAD

**Issue by eman1986** [CodeSeven/toastr#256]
it would be nice if you could set the width of the toastr notification without having to hack the css.

**Comment by TimFerrell** [comment]
Toastr returns the element that was created as a jQuery element. You can modify that as you please.

    toastr.success("awesome", "totally").css("width","500px")

**Comment by whaangbuu** [comment]
How to set the size of toastr? I've tried your example but returns .css() is not defined... thanks new in toastr.

**Comment by espiegelberg** [comment]
Your suggestion of using .css worked great for me, @TimFerrell.

Thanks!

**Comment by rodolfosouza** [comment]
just to help other 

toastr.error("title","body").attr('style', 'width: 600px !important');

**Comment by iftikhardirv** [comment]
Thanks @TimFerrell its working... 👍

**Comment by patarapolw** [comment]
Apparently, I have to set `max-width` as well, so the css becomes,

```
toastr.success("awesome", "totally").css(({
    width: "500px",
    "max-width": "500px"
})
```

Should be part of the Options.

**Comment by wan1402** [comment]
Thanks @TimFerrell and @patarapolw, I made a bit modif which worked like charm for me:
`toastr.success("awesome", "totally").css({ "width":"auto", "max-width":"100em" })`
Hope this help someone.

**Comment by john-aws** [comment]
While a useful workaround, this isn't what most users want, in my opinion. They want to be able to configure the width in options so that it applies to *all* toastrs.

**Comment by simplerezo** [comment]
Actually, only max-width is required:
`toastr.success("awesome", "totally").css("max-width","500px")`

**Comment by kapitannwel** [comment]
> Toastr returns the element that was created as a jQuery element. You can modify that as you please.
> 
> ```
> toastr.success("awesome", "totally").css("width","500px")
> ```

working perfectly at first try. thank you for your comment.

**Comment by domwal** [comment]
<style type="text/css">
        @media screen and (min-device-width: 500px) {
            .toast {
                width: auto !important;
                max-width: 600px !important;
            }
        }
</style>

**Comment by domwal** [comment]
`<style type="text/css">

        @media screen and (min-device-width: 500px) {
            .toast {
                width: auto !important;
                max-width: 600px !important;
            }
        }
</style>`
