### ISSUE TITLE
Add option to set direction of message to RTL

### ISSUE THREAD

**Issue by yevk** [CodeSeven/toastr#257]

**Comment by TimFerrell** [comment]
RTL can be achieved through CSS if I'm not mistaken.

**Comment by yevk** [comment]
It can, but in a case where you need to have the language and direction dynamically set, it becomes a bit tricky.
I think it would be better to have that functionality contained inside toastr and not having to define more CSS for it. Since toastr's div is attached to the body, you need a CSS rule to rely on a class or attribute on the body to determine the direction.

**Comment by TimFerrell** [comment]
I think that this could be a valuable contribution to the toastr project.
Is this something that you'd like to submit a pull request for? If so, let me know and we can talk implementation details.

**Comment by yevk** [comment]
I'd like to contribute, but unfortunately I'm unable right now due to lack of time.
If it's still open in a week or two, I'll get to it.

**Comment by TimFerrell** [comment]
@yevk if you care to revisit this at some point in the future please comment on this issue and we'll re-open it. 
Closing it due to lack of activity for now.

**Comment by TimFerrell** [comment]
This work was completed by @ricardobrandao in c43377c.
