### ISSUE TITLE
Null Reference when preventDuplicates is set on the demo page.

### ISSUE THREAD

**Issue by billrob** [CodeSeven/toastr#261]
I activated preventDuplicate and when I click the second post on the demo page, I get a null ref error.

**Comment by SBero** [comment]
Just to clarify, you're selecting preventDuplicates, clicking 'Show Toast', and then on the second or any additional clicks of 'Show Toast' you get the error, correct? I'm duplicating the error that way currently, and have a fix for it as well to submit as a PR.

**Comment by TimFerrell** [comment]
Confirmed.

**Comment by TimFerrell** [comment]
@SBero - looking forward to the PR.

**Comment by TimFerrell** [comment]
Resolved via PR in develop. Will merge to master shortly.

**Comment by TimFerrell** [comment]
gh-pages updated; all good here.

**Comment by alexsilveira** [comment]
Hello!

 

New message, please read <http://amal-group.org/that.php?xnp84>

 

alexsilveira@ig.com.br
