### ISSUE TITLE
How to copy the alert / error messages displayed on toasts?

### ISSUE THREAD

**Issue by KrishnaPG** [CodeSeven/toastr#266]
I am not able to see a way to copy the error messages displays using the toastr. Any click on the toast removes it from screen.

When displaying errors, it is important that users can `copy | paste` the error message displayed in the alert (so that they can communicate it with admin / support later regarding the problem) - but right now, they just disappear once the user clicks on them.

I was hoping that with the 'close button' option, the toast would go away only when clicked on the close button - but doesn't seem to be so. Clicking anywhere, no matter with or without close button - removes the toast. 

How to make it work that only when clicked on the 'close button' (the small `x button` on top right) it would go away, otherwise it would stay (that too only when `"closeButton" is set to true`?

**Comment by tomchiverton** [comment]
Set tapToDismiss to false, either in the global options or in each call.

**Comment by NaomiN** [comment]
The last link is not working.

I'm wondering if we can have a toast with the 'Copy Text' button?

Also, is it possible to have different behavior between error and other types of toast? E.g. for error I don't want to dismiss on clicking but for others I may need to be able to dismiss.
