### ISSUE TITLE
Change 'error' icon to a cross?

### ISSUE THREAD

**Issue by ConnorMcF** [CodeSeven/toastr#270]
To me it just makes more sense as the 'success' icon is a tick and a shield doesn't really fit an 'error' situation.

**Comment by TimFerrell** [comment]
Can you propose an alternate icon?

**Comment by ConnorMcF** [comment]
Oh, sorry! Forgot to include that in the post, I was thinking of a 'cross' sort of thing.

**Comment by TimFerrell** [comment]
Right, but is there a specific font library that has the glyph that you're thinking of?

**Comment by ConnorMcF** [comment]
Hmm, not sure. Maybe something like ```glyphicon glyphicon-remove```?

**Comment by ConnorMcF** [comment]
Infact, where did you get the current icons? Why not one from that pack?

**Comment by TimFerrell** [comment]
We'll evaluate this for the next major release.
Thanks for your input.
