### ISSUE TITLE
Make toastr actually full width?

### ISSUE THREAD

**Issue by nicholasalanbrown** [CodeSeven/toastr#272]
I love this plugin - great work!

How do I make the notification completely full width? It still has padding on the edges - is this because of which container it places itself into? I could override the .toastr-full-width class with width: 100vw, but I'm wondering if there's a better way to do this.

Thanks!

**Comment by nicholasalanbrown** [comment]
Nevermind, I managed it with this:
```
#toast-container.toast-bottom-full-width > div {
  width: 100%;
}
```
Why isn't this the default behavior for full-width? Is 96% width really preferable?

**Comment by TimFerrell** [comment]
Presumably for a bit of padding.
Glad you were able to make it work!
