### ISSUE TITLE
How to add a link in the toast message

### ISSUE THREAD

**Issue by yathishkrishna4019** [CodeSeven/toastr#278]
Need to provide a option to click on errors link in the toast message.

For example : "Errors found, please click on this link for more info". The "link" will be a href \ html  say having a grid of error details.

Can you please guide me to achieve the same.

Thanks.

Regards.

**Comment by TimFerrell** [comment]
There is an example in the [demo](http://codeseven.github.io/toastr/demo.html) of how to include buttons.  I know it's not an `<a>`, but it's similar. Does `<a>` not work for you?

**Comment by rurri** [comment]
Similar issue here. Getting the button in the toast is not a big deal, but getting a Meteor event click handler to respond to it is proving tricky.

**Comment by TimFerrell** [comment]
What's tricky? Does it work at all?
