### ISSUE TITLE
unClickable background area - Reconsider issue #235

### ISSUE THREAD

**Issue by nikatlas** [CodeSeven/toastr#279]
I suggest reconsidering issue #235 it was pretty important for our project and the recommended solution worked like a charm in our case. 

The @leniel 's solution doesnt seem to break my functionality niether any clickable area.
@leniel 's css
.toast-top-center
{
width: 300px;
margin: 0 auto;
left: 0;
}

**Comment by TimFerrell** [comment]
Re-opened #235.
