### ISSUE TITLE
Docs - Other Options missing 'options' param

### ISSUE THREAD

**Issue by nevf** [CodeSeven/toastr#284]
The "Other Options" section doesn't mention that you can spec a 3rd param 'options'. I thought you could only set global options which seems like a show stopper to me.

**Comment by TimFerrell** [comment]
Thanks for the suggestion.

Resolved via https://github.com/CodeSeven/toastr/pull/286.

**Comment by art-ist** [comment]
+1
... as not all toasts are the same ;-)
