### ISSUE TITLE
Question about linting toastr 3.x code

### ISSUE THREAD

**Issue by Semigradsky** [CodeSeven/toastr#300]
Hi! That question from this PR: https://github.com/CodeSeven/toastr/pull/298

You will continue to use `jshint` and `jscs` for toastr 3.x? `eslint` looks more good for es6/es7 code.

**Comment by johnpapa** [comment]
not decided yet. the team is working on v3 now

**Comment by TimFerrell** [comment]
Please subscribe to the v3 branch for more notifications on this topic.
