### ISSUE TITLE
AngularJs, RequireJs and toastr

### ISSUE THREAD

**Issue by maximdidenko** [CodeSeven/toastr#304]
Hello

I'am trying to add toastr to my app and get error "ReferenceError: toastr is not defined"

Here is my requirejs config:

requirejs.config({
    baseUrl: 'scripts/lib',
    waitSeconds: 200,
    paths: {
        'jquery': 'jquery/jquery-1.10.2',
        'toastr': 'jquery/toastr'
   },
   shim: {
       toastr: ['jquery']
  }

And when I tryng to add toastr as module dependency I got this error.

What should I do to fix this problem?

Thank you

**Comment by TimFerrell** [comment]
Please post questions on StackOverflow. If you'd like, you can provide the link here after.
