### ISSUE TITLE
how to tell toastr to display message on the top left of screen?

### ISSUE THREAD

**Issue by huangbo74** [CodeSeven/toastr#307]
I know that the toastr default target option is the body, but this doesn't seems to work when the html page contains iframe.

For example : the top of the iframe position can be far away from the screen (top : -400px;), and in this case the toastr message cannot be display on the top of screen.

Is there any way to let message always display at the top left of screen?

**Comment by rpallas** [comment]
Can you just set the `positionClass` option:
```
toastr.options = {
  // ...
  "positionClass": "toast-top-left",
  // ...
}
```

**Comment by TimFerrell** [comment]
Thanks @rpallas .
