### ISSUE TITLE
Can't see toast on iPhone or Android phone

### ISSUE THREAD

**Issue by ekwatson** [CodeSeven/toastr#312]
Do these work on mobile? I assume so, but for some reason they aren't showing up on iPhone or Android.  It may be an issue on my end, but I'm stumped.  The do show up on desktop at mobile screen sizes.

**Comment by TimFerrell** [comment]
It works correctly on my iPhone.

Do you have a specific example that it is not working under?

**Comment by ekwatson** [comment]
The demo is working, it's just not working in my implementation.  I'll have to troubleshoot a bit more.  Thanks for the response. :)

**Comment by TimFerrell** [comment]
Good luck.
