### ISSUE TITLE
Several messages at different positions

### ISSUE THREAD

**Issue by amigian74** [CodeSeven/toastr#317]
Hi,

I'm trying to display several messages at different positions at the same time - but that does'nt work.
For instance my error and success messages are shown at the top center - my infos at the bottom right.
But if an error message is still shown info messages shown up at the top center too.

Is it possible to alter teh posistion?

**Comment by TimFerrell** [comment]
While there is at least one toast on the screen, the position is locked.

When no toasts are present, the position can be modified.
