### ISSUE TITLE
SCSS/LESS refactor

### ISSUE THREAD

**Issue by ShashankaNataraj** [CodeSeven/toastr#320]
Can we refactor all of the repeated color hex codes, and write a mixin for border radius and generally clean up repeated things in SCSS/LESS? Id be willing to work on a PR for this.

**Comment by TimFerrell** [comment]
I'd be willing to take a look at an updated less file.

**Comment by ShashankaNataraj** [comment]
@TimFerrell Could I clean up the SCSS code as well? Or should I do only LESS?

**Comment by TimFerrell** [comment]
The SCSS can be the result of the built LESS.

**Comment by TimFerrell** [comment]
Closing this to focus efforts on v3.
