### ISSUE TITLE
question on module declaration 

### ISSUE THREAD

**Issue by mak962753** [CodeSeven/toastr#321]
Hey, nice work, 
but got small stupid question on this little piece of code... 

'
```javascript
function (deps, factory) {
    if (typeof module !== 'undefined' && module.exports) { //Node
        module.exports = factory(require('jquery'));
    } else {
        window['toastr'] = factory(window['jQuery']);
    }
}
```

deps variable does not seem to be used, but some explicit 'jquery' string values are used... 
not big deal though 
Thanks

**Comment by TimFerrell** [comment]
Closing to focus efforts on v3.
