### ISSUE TITLE
Semi-colon at beginning of toastr.js

### ISSUE THREAD

**Issue by AStoker** [CodeSeven/toastr#323]
There's this lingering semi-colon on line 14 of the ```toastr.js``` file, right before the function begins. 

``` javascript
...
/* global define */
; (function (define) {
    define(['jquery'], function ($) {
...
```
What's going on here? It has caused me some trouble when I try and bundle my application together into a single bundle. Is there a reason for this semi-colon?

**Comment by ryansoper** [comment]
I also noted this. Any reason behind it?

**Comment by TimFerrell** [comment]
@johnpapa - any idea?

**Comment by SBero** [comment]
I believe this is why:

http://stackoverflow.com/questions/1873983/what-does-the-leading-semicolon-in-javascript-libraries-do

**Comment by TimFerrell** [comment]
@AStoker - what issue is this causing you specifically?

**Comment by AStoker** [comment]
Specifically, I'll have to recreate the environment that was doing that to tell you (could take a bit). But what was happening generally was that I was trying to bundle our application into a single file to reduce the amount of HTTP requests (ended up going a different route in the end, looking forward to HTTP 2). So this was bundling all our source code and external modules into one file, uglifying and then minifying as it goes along (although uglifying and minifying had no hand in this problem as I tried it without). 

Well, when all was said and done, the bundled code ended up having problems with that leading semicolon. Some kind of exception error was thrown when the browser tried to load the page (and subsequently the javascript file), and it was all pointing to that leading semicolon, saying it wasn't expected. 

If I need to get a full demo up and running, I can, but you'll have to give me some time to try and get everything configured again in that state

**Comment by TimFerrell** [comment]
I'd like to see the error. If the bundled JS completes with a semicolon, it'll just do a no-op. If some other script *is* not closing an open statement, it'll close it for them.

**Comment by johnpapa** [comment]
the leading semi colon used to help with minification tools. there was a time when jsmin would run thru and if other libs had bad js, they would concat poorly. so i put the leading ; in front to help.

it is not necessary anymore. if another lib sucks, then , oh well :)

feel free to pull it out Tim

**Comment by TimFerrell** [comment]
Hey @AStoker - want to make the world's smallest pull request?

**Comment by AStoker** [comment]
@TimFerrell - Mission accomplished. Is there some kind of award for smallest pull request? If not, I'm thinking one should be made... :)

**Comment by TimFerrell** [comment]
I'll mull something over. 😜

Could you please re-submit the change to the develop branch, though?

**Comment by AStoker** [comment]
Absolutely, my mistake.
