### ISSUE TITLE
How to make it show in the center position except "top, bottom, left, right"?

### ISSUE THREAD

**Issue by sunblognuke** [CodeSeven/toastr#33]
Maybe I missed something but anyone how to make the notification show in the center position except that "top, bottom, left, right"? Thanks a lot.

**Comment by weituotian** [comment]
there is no `left: 50%;`

**Comment by rohitgrover** [comment]
Thanks. It works

**Comment by kavinda1995** [comment]
> try to add this class to css:
> .toast-top-center {
> top: 12px;
> margin: 0 auto;
> left: 50%;
> }
> 
> and then set toastr.options
> eg:
> toastr.options = {
> timeOut : 0,
> extendedTimeOut : 100,
> tapToDismiss : true,
> debug : false,
> fadeOut: 10,
> positionClass : "toast-top-center"
> };

No need of adding `left: 50%;`  😃
