### ISSUE TITLE
Loose Bower Dependency Definition?

### ISSUE THREAD

**Issue by gravidThoughts** [CodeSeven/toastr#340]
Hi,

I am implementing Bower for a new VS 2015 front end project.

Toastr#2.1.2 has its dependencies deinfed in `bowser.json` as follows:

```
dependencies: {
    jquery: '>=1.6.3'
}
```

If I understand Bower correctly, the next time I perform an update, if jQuery 3.0.0 production is live, it will update to 3.0.0.

Considering jQuery 3.0.0 is only alpha, how can you be certain that it will be backwards compatible with Toastr 2.1.2?

**Comment by TimFerrell** [comment]
Good call. Would you like to create a PR to clamp the version to <3?

**Comment by gravidThoughts** [comment]
Sure! Give me a little time. I have never contributed, but seems like now would be a good time to figure out the process :).

**Comment by TimFerrell** [comment]
Just be sure to contribute to the develop branch and not master. 






On Tue, Aug 18, 2015 at 10:00 AM -0700, "Matthew Copeland" <notifications@github.com> wrote:












Sure! Give me a little time. I have never contributed, but seems like now would be a good time to figure out the process :).

**Comment by gravidThoughts** [comment]
This is in a separate repository. I have issued a pull request ther.

https://github.com/johnpapa/toastr-bower/pull/7

**Comment by TimFerrell** [comment]
Toastr bower is updated from this repo. 

Please make the change here.

**Comment by gravidThoughts** [comment]
My apologies, I don't see the bower.json file anywhere. Do I just create a new one and assume it will be version 2.1.3?

**Comment by TimFerrell** [comment]
My mistake.
