### ISSUE TITLE
gh-pages branch needs to be updated from master

### ISSUE THREAD

**Issue by harrywang** [CodeSeven/toastr#342]
I made a screencast for this: http://screencast.com/t/kAxp1ubj4oNV

Is it possible to clear the message when I click any part of the screen? Thanks a lot for your help.

**Comment by TimFerrell** [comment]
All sorts of things look strange about your attached video.
Can you post a fiddle of this behavior?

**Comment by harrywang** [comment]
I don't know what you mean about a fiddle of this behavior. Essentially, while the messages are shown, I cannot check the options (such as close button, debug) that are on the same line as messages - the messages are getting the focus - nothing on the same height can be clicked till you close those messages. I hope this is clear enough. Thanks!

**Comment by harrywang** [comment]
Hope this following explains what I meant:
![screenshot 2015-08-24 10 14 16](https://cloud.githubusercontent.com/assets/595772/9442328/5fa49f6e-4a49-11e5-96e5-26628feb393e.png)

**Comment by TimFerrell** [comment]
I have no way to reproduce the issue that you're reporting.

Can you provide a way for me to do that?

**Comment by harrywang** [comment]
I just tried again using two browsers at http://codeseven.github.io/toastr/demo.html, same issue - make sure you choose top center and open a few messages so that the message will cover a few options.

**Comment by TimFerrell** [comment]
I understand your issue.

This is not an issue in the demo master or develop branch, but is an artifact of the demo.html file not being updated in the gh-pages branch.

**Comment by harrywang** [comment]
I am using the latest version (CodeSeven-toastr-2.1.2-3-g8bbd8db) and still have this issue - did you mean the demo page was not using the latest version of toastr?

**Comment by TimFerrell** [comment]
Demo page now updated. Issue no longer present.

**Comment by harrywang** [comment]
@TimFerrell yes. the demo page is ok now - could you please let me know how you fixed it? I updated to the latest version and the problem was still there. Thanks a lot for your help.

**Comment by TimFerrell** [comment]
Check out the commits on Aug 26: https://github.com/CodeSeven/toastr/commits/gh-pages

**Comment by harrywang** [comment]
problem solved after update the CSS and JS - thanks a lot for your help!!
