### ISSUE TITLE
Demo has errors

### ISSUE THREAD

**Issue by bzuillsmith** [CodeSeven/toastr#344]
The demo is generating strings for numeric properties. This causes adjustments to ```showDuration``` and other numeric properties to have no effect, and the example options output is wrong.

**Comment by TimFerrell** [comment]
Will review this soon.

**Comment by ShashankaNataraj** [comment]
@TimFerrell I want to fix this one!

**Comment by TimFerrell** [comment]
Go for it!

**Comment by ShashankaNataraj** [comment]
Here you go :dart:
