### ISSUE TITLE
Toast opening in the same place where the last one occured

### ISSUE THREAD

**Issue by brandflownet** [CodeSeven/toastr#346]
I have 2 buttons: 
A - opening success toast in top left corner 
B - opening warning toast in bottom right corner

When I quickly click A and B one after the other both toast are showing in the same place. If I do it slowly everything work like a charm. So until previous toast disappears, any new toast will  show in same location. 

Demo below is also having same issue: 
http://codeseven.github.io/toastr/demo.html

**Comment by TimFerrell** [comment]
Toasts are held within a container. If the container has 1 or more toast within it, toasts will be positioned where the existing container is.

For example, if you generate toast A in top left, and then toast B in the bottom right and the container has not yet been removed, then the position you provide will not be respected until the container has been removed from the DOM.
