### ISSUE TITLE
"Add button to force clearing a toast..." option in demo is misleading

### ISSUE THREAD

**Issue by dennissheppard** [CodeSeven/toastr#350]
"Add button to force clearing a toast" option in demo doesn't mention that toastr doesn't natively support an "ok" button (or in the case of the demo, a "yes" button) to close a toast.

The demo uses the following snippet to make that work.

```
if ($toast.find('.clear').length) {
       $toast.delegate('.clear', 'click', function () {
             toastr.clear($toast, { force: true });
       });
}
```

The demo should make mention of that extra snippet (or it'd be cool if the library did support it natively, as long as you used the 'clear' class in your button or something).

**Comment by johnpapa** [comment]
You can use the close button option too, as shown in the demo , to add an X. Or you can add a button of your choice, as shown in the demo, to do a custom event you bind to. 

Open Source works by collaboration. The spirit is to be helpful and add content. Feel free to make a PR and extend the demo or add to the readme so all benefit.

**Comment by dennissheppard** [comment]
Yeah, the X is great, but that's not what the "Add button to force clearing" option shows you using.  It uses the "button of your choice", but it's unclear that you need a custom event to bind to that button, since the demo doesn't mention that at all.

My apologies for appearing uncollaborative or unhelpful... the tone of my post was 98% tongue in cheek.

I will, though, look into adding a little note to the demo.html on selecting that option and submitting a PR.

**Comment by TimFerrell** [comment]
Thanks Dennis. Looking forward to the PR.

**Comment by ChandanSinghBajetha** [comment]
Hi,

Can we add Two button like "Yes" or "No" and want to do some action on click of this two buttons.
For Example:-
Message : Your changes is not save, Do you want to continue?
"Yes" "No"
Yes click: Without save redirect on another page.
No Click: Will be in same page.

**Comment by TimFerrell** [comment]
Those are not candidates for toastr, but you are capable of adding them yourself if you see a need.
