### ISSUE TITLE
Don't rely on a id="toast-container" element

### ISSUE THREAD

**Issue by ibc** [CodeSeven/toastr#357]
This is not cool at all:

``` js
$container = $('#' + options.containerId);
```

Please don't force the user/app to give a specific `id` attribute to toastr. Instead let the user/app to select a HTML element without requiring it to have an ìd`attribute. In other words, toastr should not require any HTML element with a specific`id` attribute.

Imagine por example the case in which a 3rd party widget uses toast and the website also uses toast. They would basically conflict.

**Comment by ShashankaNataraj** [comment]
+1!

**Comment by TimFerrell** [comment]
Is this an actual use case? Using two toastr instances at the same time?

**Comment by ibc** [comment]
You may want to provide external websites with your "app-widget", which may use toastr. The website (not on your control) may also use toastr.

**Comment by TimFerrell** [comment]
You can specify the container id using this option: https://github.com/CodeSeven/toastr/blob/master/toastr.js#L157
