### ISSUE TITLE
Pin feature

### ISSUE THREAD

**Issue by SamGraber** [CodeSeven/toastr#365]
My team recently moved over to using toastr from pnotify, and one of the things that we would like to see is the ability to pin toasts so we can capture a screenshot to help in identifying bugs. Would it be possible to add an optional pin button that would function similar to the close button, but trigger the toast to stay on the page instead? (Consumer sets pinButton to true to enable the button) 

Even cooler would be to have the button only appear when the user mouses over the toast, so only support users could care about it.

If it would be helpful, I could take a stab at implementing it myself. It seems like it would want to tie into the `stickAround()` function, which is used to keep it around on hover.

**Comment by TimFerrell** [comment]
This seems interesting.

If you were interested in implementing it, please model it as though it were a non-default option using the options object.

**Comment by ShashankaNataraj** [comment]
@TimFerrell May I submit a PR for this? Looks like this could interesting to implement!

**Comment by TimFerrell** [comment]
Sure. Would like to see @samgraber push a PR in too.

**Comment by TimFerrell** [comment]
Given the lack of activity on this, I'll be closing the issue. 
If there is interest in the future please note this issue.
