### ISSUE TITLE
Remove closure from gulp

### ISSUE THREAD

**Issue by ShashankaNataraj** [CodeSeven/toastr#369]
Was trying to get the tests up and running when I saw closure compiler being invoked from gulp.

According to @TimFerrell's comment on : https://github.com/CodeSeven/toastr/pull/339 closure needs to be removed. Can I make a PR?

**Comment by TimFerrell** [comment]
Sure - if that'd help the tests.

**Comment by TimFerrell** [comment]
Closure is not in 2.x releases. v3 will be targeted for cleanup soon.
