### ISSUE TITLE
Option to disable hover events altogether

### ISSUE THREAD

**Issue by john-sanders-2** [CodeSeven/toastr#372]
**Summary:** I want toastr to work as-is, but disable the hover events.

My use case involves showing a toastr warning for a specific amount of time, but I don't want the hover event to dismiss it. I want it to dismiss itself at the end of the countdown, or dismiss when the user clicks it. I can't seem to find a combination of settings that accomplish this.

It seems like an option could be added, `closeOnHover`, with a default value of `true`. So if set to `false`, no hover events are set up.

**Comment by john-sanders-2** [comment]
I would be happy to submit a pull request and tests if you'd like.

**Comment by TimFerrell** [comment]
I'd be interested in seeing a pull request for this.

**Comment by john-sanders-2** [comment]
I've got the changes wrapped up, and 2 new tests written. I'm fairly new to Git, do I do the pull request to Master?

**Comment by TimFerrell** [comment]
Thanks for asking; submit to develop.

**Comment by john-sanders-2** [comment]
Pull request submitted.

**Comment by TimFerrell** [comment]
Thanks!
