### ISSUE TITLE
Prevent close on click

### ISSUE THREAD

**Issue by Santiago-Rocha** [CodeSeven/toastr#373]
@johnpapa  is there a way to prevent close toastr on click ?

**Comment by arahansen** [comment]
Have you tried

 ```toastr.options = {
  "onclick": function(event) { 
    // could use event.preventDefault(); 
    // to stop the toast from closing when the toast message is clicked
  },
}```

**Comment by jazayerim** [comment]
@Santiago-Rocha Did you find any solution for this bug?

**Comment by mg1075** [comment]
No solution? This seems like important functionality to include.

**Comment by alanhamlett** [comment]
There is a `tapToDismiss` option that when set to false prevents the toast from closing when clicked.

**Comment by nayzawoo** [comment]
Try this

```js
      toastr.options = {
        tapToDismiss: false,
        onclick: false,
        closeOnHover: false,
      };
```

**Comment by genius257** [comment]
Currently i throw a new error in the onclick to prevent it from closing.

**Comment by Akbarics** [comment]
Prevent close Toastr on Click by this code:
  $.fn.noop = function () { return this; };
         toastr.options.hideMethod = 'noop';

**Comment by grantiverson** [comment]
@alanhamlett Is right. Setting `tapToDismiss`  to `false` prevents toasts from closing on click. @TimFerrell

Here's an example: https://codepen.io/grantiverson/pen/BVZopw
