### ISSUE TITLE
Toastr Container

### ISSUE THREAD

**Issue by tbragaf** [CodeSeven/toastr#375]
Hi all!

It seems to me that after a toast is rendered (and then disappears) the container also disappears with it.
And, after that, my old container stops existing, and following toasts will render inside the default container with fixed position.

Is there anything I should be aware of?

Stay awesome,
tbragaf

**Comment by appjitsu** [comment]
I have the same issue.

**Comment by tbragaf** [comment]
I hacked this behaviour with an empty span inside the container xD

**Comment by appjitsu** [comment]
@tbragaf hah nice!

**Comment by acshef** [comment]
The container should be RECREATED once a new toast appears. Specifically, the `toastr.xxxxxx()` functions will internally call the `notify()` function. Within `notify()`, it gets the container using the internal function `getContainer(options,true)`. The second parameter being `true` means that it will first try to find an existing container, and if not then it will create the container and return that.

**Comment by TimFerrell** [comment]
This isn't an issue - the container is removed by design once there are no remaining toasts.

**Comment by tbragaf** [comment]
@TimFerrell So how can I achieve my purpose?

**Comment by TimFerrell** [comment]
What's your problem, specifically?

**Comment by tbragaf** [comment]
@TimFerrell I don't want the container to disappear from my div element.
I only managed to do that by spawning a span element inside the container, which is an ugly hack.

**Comment by TimFerrell** [comment]
Why are you trying to prevent the container from closing?

**Comment by tbragaf** [comment]
@TimFerrell because I want the toasts to always appear inside it.

**Comment by TimFerrell** [comment]
The container will recreate itself automatically. Maybe I'm not asking the right questions here but can you please explain why you don't want this to happen?

**Comment by tbragaf** [comment]
In my sample, the container recreates at the default position: body
And I need it inside another tag

**Comment by TimFerrell** [comment]
Sorry for the slow response. You can specify the element that the container appears within - is that not happening for you?

**Comment by tbragaf** [comment]
@TimFerrell How so?

I tried with:
```html
<div id="toast-container">
    <!-- Only way to prevent the destruction -->
    <span></span>
</div>
```

**Comment by JasonLawrenceDuncan** [comment]
I ran into this same issue today. @tbragaf 's hack does work, but this sure seems like a bug to me. If the user provides a "target", you shouldn't delete it (or at least add an option to override deletion). I want to position the container relative to a parent div, not have it be dynamically injected at the bottom of the DOM.
