### ISSUE TITLE
Refactor specification of styles for easier overriding

### ISSUE THREAD

**Issue by ambischof** [CodeSeven/toastr#379]
It's kind of hard currently to change certain styles without changing code. 

- separate your necessary vs styling vs icon css
  - The way they're jumbled together makes it hard to override. Purely aesthetic css like color: #ffffff should not be together with the positioning css in  the highly specific selector #toast-container > div. The color coordinates with background color specified elsewhere, so they should be together so they are overridden together. If I wanted to use bootstrap's 'alert-info' instead, i'd have to hack to get around this. 
  -  icon classes should be separate too. I might want to use the icon but not the background color or visa versa. Instead of using padding to make room for a background image, it might be better to use something similar to font-awesome or glyphicon's approach of making an element for the icon and using ::before or ::after pseudo-elements to populate the icon. This would greatly increase the flexibility of the layout.

- Allow for custom templates.

**Comment by nljuba** [comment]
second this!

**Comment by jordan112** [comment]
+1

**Comment by kpicaza** [comment]
+1

**Comment by TimFerrell** [comment]
Thanks for the feedback, this is something that'll be considered in v3.
