### ISSUE TITLE
Two icons problem

### ISSUE THREAD

**Issue by murbano83** [CodeSeven/toastr#388]
As you can see, shows two different icons on notification:

![captura de pantalla 2016-01-03 a las 2 49 32](https://cloud.githubusercontent.com/assets/4415557/12076950/b62718fc-b1c4-11e5-864d-bae3bbdd44c4.png)

![captura de pantalla 2016-01-03 a las 2 50 45](https://cloud.githubusercontent.com/assets/4415557/12076952/d20eebd0-b1c4-11e5-9326-272182467e60.png)

**Comment by RedaBenh** [comment]
Same issue in my rails app

**Comment by ericmerl** [comment]
If I had to guess, you've probably got a CSS conflict. I was using a pre-built theme that included the Toastr plugin, and some of the custom styling in that theme was causing two icons to appear.

Here's the code that I removed solved the issue:

`#toast-container > .toast-warning:before {
  content: "\f0e7";
}`
`#toast-container > .toast-error:before {
  content: "\f071";
}`
`#toast-container > .toast-info:before {
  content: "\f005";
}`
`#toast-container > .toast-success:before {
  content: "\f00C";
}`

Do some digging in your CSS, and I bet you'll find the same sort of thing going on.

**Comment by deven003** [comment]
@murbano83 loading toastr css before any other css, fix this problem for me.

**Comment by RejetiPraveen** [comment]
Nothing to be done with any of the above.Just keep your
toastr css immediately after boostrap(if using)  and before any other css links.Its will work without any issues.

likes this: 

```
     <link href="~/Content/bootstrap.min.css" rel="stylesheet">
     <link href="~/Content/plugins/toastr/toastr.min.css" rel="stylesheet">
```

....remaining links here after.....comes
