### ISSUE TITLE
preventDuplicates does not work for arrays

### ISSUE THREAD

**Issue by iranianpep** [CodeSeven/toastr#389]
Not sure if this a bug or an intended specification, but for example if I pass this array to toastr:
["Username is required.", "'' is not a valid username.", "Email is required.", "'' is not a valid email."]

preventDuplicates = true does not work. To solve it I used join() to convert the array to string.

**Comment by john-sanders-2** [comment]
Can you provide a snippet of code to illustrate how you are using toastr to pass the array?

**Comment by iranianpep** [comment]
Hi John,

Thanks for the quick response. This my ajax call:

      $.ajax({
            type: 'POST',
            data: data,
            dataType: 'json',
            url: this.getAttribute('data-url'),
            headers: {
                Accept: "application/json; charset:utf-8"
            },
            success: function(response) {
                if (response.success === true) {
                    if (response.message !== undefined) {
                        // convert array to string using join
                        if (response.message instanceof Array) {
                            response.message = response.message.join('<br>');
                        }

                        toastr.success(response.message, 'Success');
                    }
                } else {
                    console.log(response.message);
                    // convert array to string using join
                    if (response.message instanceof Array) {
                        response.message = response.message.join('<br>');
                    }

                    toastr.error(response.message, 'Error');
                }
            },
        });

As you see I used a workaround to convert array to string. And also this is console log output:
`["Username is required.", "'' is not a valid username.", "Email is required.", "'' is not a valid email."]`

**Comment by TimFerrell** [comment]
Passing arrays as a message isn't a use case I've ever heard before. @iranianpep - I'm curious why you'd do this rather than forming a string for the toast manually, or create a toast for each string.

**Comment by iranianpep** [comment]
I return response.message as an array since it is more flexible to work with, specially for validation messages. Initially I was testing toastr by simply passing the array which still displayed the message, however spent some time figuring out why preventDuplicates didn't work. Like I said, now I implode the array and it works fine.
