### ISSUE TITLE
CDN JS "latest" appears to be out of date

### ISSUE THREAD

**Issue by scottescue** [CodeSeven/toastr#392]
The Debug and Minified links in gh-pages/index.html point to `//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/...`  However, "latest" isn't serving up version 2.1.2.  The HTML escaping option added in 2.1.2 isn't included in the "latest" JS file.

I discovered this today while trying to update one of my projects to take advantage of the new escaping feature.  I realize this most likely isn't an issue with the source.  But, it caused me a fair amount of troubleshooting and I'd like to see it corrected.

**Comment by TimFerrell** [comment]
We've had communication with CDN JS in the past and they expressed an interest in no longer supporting the latest tag for repos (in memory serves correctly.)

Recommendation is to take a specific version number from CDN JS, rather than latest. Will follow up.

**Comment by TimFerrell** [comment]
https://github.com/cdnjs/cdnjs/issues/8472

**Comment by TimFerrell** [comment]
CDN JS has updated to 2.1.2 as latest.
