### ISSUE TITLE
ARIA speaking double up

### ISSUE THREAD

**Issue by mike-nelson** [CodeSeven/toastr#395]
When I use toastr with VoiceOver on iOS it is saying the message 2 or 3 times. Tested on demo page.

It is using `aria-live=polite role=alert`

Not sure what is wrong with that, seems sensible to me. It's not very polite though, saying it several times! 

Maybe toastr sets the inner html twice or something?

**Comment by mike-nelson** [comment]
Found the bug. It causes double speaking using both `aria-live` and `role=alert` 

Recommend removing the role=alert.

Further, it would be good for "error" to show `aria-live=assertive` and "info" messages to show `aria-live=polite`

**Comment by TimFerrell** [comment]
Hey @mike-nelson - would you be interested in creating a PR with your changes?

**Comment by TimFerrell** [comment]
All done.

**Comment by mike-nelson** [comment]
Good one. Thanks for implementing!

**Comment by TimFerrell** [comment]
Just pushed tests up.
