### ISSUE TITLE
Change toast opacity

### ISSUE THREAD

**Issue by Sigmanor** [CodeSeven/toastr#396]
When I try to change the opacity of message in this way:
`#toast-container > div {opacity: .95!important;}`
Show/hide animation doesn't work. How correctly change the opacity?

_Use in app built in [electron](http://electron.atom.io/)._

**Comment by TimFerrell** [comment]
Can you explain what you mean by "doesn't work"? What specifically does or does not happen?

**Comment by sergchernata** [comment]
I know this is an old issue, but I have the same problem. What he meant was that the animations stop "fading in" and "fading out" if opacity is set to 1 via css.

**Comment by farhadhesari** [comment]
You can do something like this :

`.toast-error {
  background-color: rgba(255,111,105,0.95) !important;
}`
