### ISSUE TITLE
iOS hover bug

### ISSUE THREAD

**Issue by johnw86** [CodeSeven/toastr#398]
We had some bizarre anchor issues reported by our users on iOS devices, which required them to tap twice to action links. After a fair amount on investigation throughout our source code I came to the conclusion it was something within the toastr css file causing the issue. By the process of removing selectors as none seemed obvious on initial review it was the selector: _#toast-container > :hover _

Soon as I removed that selector the issue went and links now functioned with a single tap as expected. To keep the hover styling I just amended the selector to be #toast-container > div:hover.

I have done a small pr with the fix: #397 

John

**Comment by johnw86** [comment]
Updated pr #400

**Comment by TimFerrell** [comment]
Thanks @johnw86
