### ISSUE TITLE
While a toast is visible, next toast ignores own settings

### ISSUE THREAD

**Issue by avalanche1** [CodeSeven/toastr#401]
If I call a toaster with `positionClass: "toast-top-full-width"` and while it is visible I run `positionClass: "toast-bottom-full-width"`- they both will be shown on top.
You can test it on demo page.

**Comment by csakis** [comment]
I had the same experience.

**Comment by blackholegalaxy** [comment]
I have the same problem here.

**Comment by TimFerrell** [comment]
This is due to toasts sharing the same container. Because the container still exists from the previous toast, all toasts generated while that container is active will end up within that container. If you wait for the container to remove from scope, then the next toast will appear in the requested container.

**Comment by avalanche1** [comment]
Well, this is really awkward. This essentially means that I can only have several IDENTICAL toasts at a time. I think this should be patched and this issue reopened until then.

**Comment by TimFerrell** [comment]
What's the use case for showing several identical toasts?

**Comment by csakis** [comment]
They are not identical toasts. That's the whole point. I use websocket technology to get notifications from the server. If it's a general notification, I use a small toast at the bottom right corner. If it's an important/danger message from the server, I want my toast in the top middle, so the user does not miss it. 
I cannot control when these messages coming from the server. It depends on other users. However, if two of these messeges overlap, then they will be identical.

**Comment by TimFerrell** [comment]
To be clear, when you're saying identical, you just mean positioned in the same place?
If not, can you please provide an example of the behavior you're describing?

**Comment by csakis** [comment]
Yes, I meant same position. Edited my comment, too.

**Comment by TimFerrell** [comment]
Understood. However, this is the current design of toast. One container at a time. 
I'm not against using multiple containers, and will likely implement something in v3 to remediate this issue, but unless someone is will to contribute a PR to allow this functionality in 2.x, it is not currently possible.

**Comment by avalanche1** [comment]
Well let's keep this on the roadmap at least and keep this issue open as a feature request until it's implemented.
