### ISSUE TITLE
Zepto support

### ISSUE THREAD

**Issue by aotian16** [CodeSeven/toastr#406]
Nice project!
But I want to use this in Zepto, how can i use ?

**Comment by johnpapa** [comment]
its just javascript.

**Comment by aotian16** [comment]
@johnpapa Sorry, but I am not familiar with js.
I do not want use jquery in my project, and use Zepto instead.

**Comment by TimFerrell** [comment]
V3 plans to remove the jQuery dependency. If you require no jQ, then wait for that release.
