### ISSUE TITLE
Position not corrected.

### ISSUE THREAD

**Issue by Tadej0** [CodeSeven/toastr#412]
Hi,
I am trying to set the notifications to show in the bottom right, but they are not showing. I looked at various "solutions" but nothing worked. I also tried to show the toast notification in any other place instead of the default top right, but nothing worked. 
They are constantly being shown at the top right corner. What am I doing wrong?
My code is in the attached file:

[tadej1.txt](https://github.com/CodeSeven/toastr/files/216715/tadej1.txt)

**Comment by Mobius1** [comment]
You need to set the options before calling the notification:

`toastr.options {
...
}

toastr.success("Are you the six fingered man?")`
