### ISSUE TITLE
Disable toastr stacking

### ISSUE THREAD

**Issue by danmv** [CodeSeven/toastr#414]
Here it is my use case: 
I have an app that when users switch between tabs it triggers the toastr indicate that any change made inside that tab was saved. 

In the case when I users switches back and for between tabs the toastr show on on top of each other. I  have been trying to find a way to prevent that but have not been able to. 

Ideally, when multiple toastr have been trigger I want to only show on at a time at all times. Can anyone  indicate me how to accomplish this ?

**Comment by judowalker** [comment]
Take a look at the following from my fork of toastr:
https://github.com/judowalker/toastr/commit/385bef10ea56a14a98a504f3116c4f1c3ba94fe0

It will stack the toastr messages.

**Comment by TimFerrell** [comment]
You can grab the hook for the toast once it's created and then cancel/hide it at will. You could also leverage the preventDuplicates option if your messages titles match.
