### ISSUE TITLE
Toastr.scss is css

### ISSUE THREAD

**Issue by luisgrandegg** [CodeSeven/toastr#415]
Hi!
Is it ok for you if I update the scss file so it's a translation of the less files, with variables and all that stuff? Right now it is just plain css, so I have to override the rules to get the styling I want

**Comment by TimFerrell** [comment]
It's my understanding that we provide the SCSS file for legacy reasons, and it should be a straight copy of the compiled LESS files. I'd really like to not maintain two pre-compiled stylesheets unless there was a compelling reason to do so.
