### ISSUE TITLE
toastr object is not associated with 'window', how to use it in this case?

### ISSUE THREAD

**Issue by dongzhi-yang** [CodeSeven/toastr#421]
I have  toast.js installed and the problem is i can’t use toastr object directly.
I did some investigation and found that the toastr object is not associated with ‘window’.

here is the last lines of code in toast.js, I assume it decides where toastr object is associated.I have added 2 console.log in the 2 branches of if.
—————————–
(typeof define === ‘function’ && define.amd ? define : function (deps, factory) {
if (typeof module !== ‘undefined’ && module.exports && typeof require === ‘function’) { //Node
module.exports = factory(require(‘jquery’));
console.log(“hello 1”);
} else {
window[‘toastr’] = factory(window[‘jQuery’]);
console.log(“hello 2”);
}
})

——————————

the console returns “hello 1”.
so obviously window[‘toastr’] never executes.

I am in a Meteor environment on top of node.js jquery. could you let me know how to use toastr in this case? thanks very much

Regards

Don

**Comment by TimFerrell** [comment]
It looks like the issue here is that toastr believes that it is running within Node (which is valid), but the block that is being executed by Meteor is generally used by the test suites. If you can assist in identifying a better way to identify Meteor usage, then I'd be interested in a PR.
