### ISSUE TITLE
toastr.options.onHidden not work

### ISSUE THREAD

**Issue by xr0m3oz** [CodeSeven/toastr#425]
`
 toastr.success('Shipment unloaded.', false,params);

toastr.options.onHidden = function() { console.log("onHide");location.reload(); }
`
Not work.

**Comment by mallikarjuna909** [comment]
Make sure your parameters in your success &
// Define a callback for when the toast is hidden
toastr.options.onHidden = function() { console.log('onHide'); }

**Comment by TimFerrell** [comment]
Thanks, @mallikarjuna909.
