### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by rheimus** [CodeSeven/toastr#426]
Could support be added for jQuery's animate function?

Something like toastr.options.hideOptions = {"left":"200px", "top":"20px"}, to add custom properties to the function call.

```
function hideToast(foo) {
    var customOptions = options.hideOptions;

     return $toastElement[method]({
                        duration: duration,
                        easing: easing,
                        // insert customOptions
                        complete: function () {}
     });
}
```

**Comment by TimFerrell** [comment]
Support already exists for using existing jQuery animation styles.
If you want something else, you can accomplish using CSS.
