### ISSUE TITLE
Swap title and text

### ISSUE THREAD

**Issue by visavi** [CodeSeven/toastr#427]
It so happens that sometimes there is no message, but only the title and it looks bold text
I would like to go first mandatory title. and then the message text

```
toastr.error('Text message', 'Title')
```
Is it possible to swap the title and text messages
```
toastr.error('Title', 'Text message')
```

**Comment by TimFerrell** [comment]
This would be a substantial change to the existing interface for limited benefit.
If you want the text to appear in the text area, just provide an empty string as the title.

**Comment by visavi** [comment]
as a temporary option I did so
who could be useful

```js
function notify(type, title, message, optionsOverride) {
	return toastr[type](message, title, optionsOverride);
}```
