### ISSUE TITLE
Show until user dismisses

### ISSUE THREAD

**Issue by kunkinkan** [CodeSeven/toastr#428]
I don't want a showDuration, but keep showing it until the user clicks the close button. Is this possible?

**Comment by TimFerrell** [comment]
Checkout timeOut and extendedTimeOut properties.

Tim Ferrell

**Comment by mallikarjuna909** [comment]
Hi Kunkinkan,
Try once,

toastr.options = {
  **"closeButton": true,**
  "debug": false,
  "newestOnTop": false,
  "progressBar": false,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  **"timeOut": 0,
  "extendedTimeOut": 0,**
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut",
  **"tapToDismiss": false**
}
