### ISSUE TITLE
Allow Tost Close

### ISSUE THREAD

**Issue by hosseinzade** [CodeSeven/toastr#430]
Add  allowTostClose option for enable and disable close  toaster.

**Comment by mallikarjuna909** [comment]
Hey hosseinzade!
You can close toast by using **"tapToDismiss": true** in the toastr.options
(or)
You can use add button to force clearing a toast,  "timeOut": 0,  "extendedTimeOut": 0, "tapToDismiss": false in n the toastr.options.
