### ISSUE TITLE
Close button callback?

### ISSUE THREAD

**Issue by benheymink** [CodeSeven/toastr#432]
Apologies if I missed this, but is there a way to provide a function to execute when the close button was clicked? I can provide a method that gets executed when the toastr itself is clicked:

    toastr.success('Some text', 'Some title', {onclick: self.someMethod});

Is there something similar to ONLY fire when the close button has been clicked?

**Comment by TimFerrell** [comment]
Looks like not, but the change should be very simple to do yourself: https://github.com/CodeSeven/toastr/blob/master/toastr.js#L276

If you think this would be valuable to the community, please consider creating a PR.
