### ISSUE TITLE
iOS touch interference 

### ISSUE THREAD

**Issue by zparduhn** [CodeSeven/toastr#436]
When a toast is present, touch is disabled. Once the toast is no longer displayed, touch is enabled.

**Comment by TimFerrell** [comment]
Is this a question?

**Comment by zparduhn** [comment]
Yeah, is that supposed to happen?

**Comment by TimFerrell** [comment]
Do you have an example illustrating this?

**Comment by zparduhn** [comment]
Once the post is returned, a toastr shows success with the amount that was added. While the toastr is present, you can't touch the logout button or key in new values. The user has to wait until the toastr is no longer present, and then they can click on additional buttons or log out. They report to me that the app feels slow and unresponsive, when in reality it only unresponsive when a toastr is displayed. 
//Promise
`service.addSnack(amountObj).then(function(response) {
            toastr.success(amount + " added")
            $scope.getTotal();
            $scope.input = '';
        })`
//Config
`angular.extend(toastrConfig, {
            autoDismiss: true,
            containerId: 'toast-container',
            maxOpened: 4,
            newestOnTop: true,
            positionClass: 'toast-top-center',
            preventDuplicates: false,
            preventOpenDuplicates: true,
            target: 'body',
            timeOut: 2000,
        })`

**Comment by TimFerrell** [comment]
@pickledyamsman - can you take a look at this?

**Comment by TimFerrell** [comment]
Resolved in develop branch by an existing commit. Planning on releasing soon.
