### ISSUE TITLE
Support for jquery 3.1.0 in npm version of toastr

### ISSUE THREAD

**Issue by aocneanu** [CodeSeven/toastr#449]
I use bower for managing my packets and it seems that on npm there is a slightly different version of toastr that needs jquery < 3. Is this so or I am doing something wrong?

**Comment by radiolips** [comment]
I'm having the same problem. toastr's bower file has this:
```
 "dependencies": {
		"jquery": ">=1.6.3 <3"
  },
```

Is there any way the `<3` can be removed?

**Comment by TimFerrell** [comment]
Yes, just open a PR against the develop branch.

**Comment by radiolips** [comment]
Oh, wouldn't that be nice, @TimFerrell ! Unfortunately, it appears that the `bower.json` file is managed solely through johnpapa/toastr-bower. I've put in a PR there. The `bower.json` file should probably be managed in this main repo and copied over during releases to help maintain it. I, for one, was a little confused when looking for the file to modify.

**Comment by TimFerrell** [comment]
No sweat, I maintain both. Push to develop. I'll get it to master and the bower repo.

**Comment by TimFerrell** [comment]
To elaborate, the bower repo is a downstream copy of the master branch of this repo. Changes shouldn't happen directly on that repo.

**Comment by radiolips** [comment]
@TimFerrell Understood, that's what I assumed you were doing. I was just speaking specifically about `bower.json`, which is not currently present in this repo. But if this PR gets merged in, starting now it'll be there!

**Comment by TimFerrell** [comment]
Cool, merged!

**Comment by tacooper** [comment]
when is this fix going to be merged into master (and thus available in the bower repo)? when using `"toastr": "latest"` in my project's bower.json dependencies, jQuery 3 is still not allowed unless I manually edit Toastr's bower.json as well.
