### ISSUE TITLE
CDN reference is has 404 error

### ISSUE THREAD

**Issue by Solatrus** [CodeSeven/toastr#451]
The CDN reference for Toastr (debug and minified) is currently returning an nginx 404 error. Is the CDN having server issues?

https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js

Also, is there a mirror?

**Comment by agkunz** [comment]
Same issue here, been happening since at least yesterday.

**Comment by TimFerrell** [comment]
Referenced in #453.

Please follow updates there.
