### ISSUE TITLE
Toast not showing on iphone 6s Safari

### ISSUE THREAD

**Issue by maddo7** [CodeSeven/toastr#454]
Hello,
I just checked the demo with my iphone 6s using the safari browser and upon clicking the button nothing happens.
Everything works when using the chrome browser.

Is there a solution to this?

**Comment by TimFerrell** [comment]
I just tried it on Safari, on iOS. Works correctly.
What version of iOS?

**Comment by TimFerrell** [comment]
Browser Stack also shows no problems.
<img width="448" alt="screen shot 2016-08-22 at 9 39 14 pm" src="https://cloud.githubusercontent.com/assets/189421/17877372/d77e64a8-68b0-11e6-9af4-0bc79b66fe6f.png">

**Comment by maddo7** [comment]
I have iOS 9.3.4(13G35).
I just found out the iOS adblocker "Blockr" is blocking this script so it didn't work because of that.
