### ISSUE TITLE
Add redirectUrl to optionsOverride

### ISSUE THREAD

**Issue by rnitame** [CodeSeven/toastr#461]
## before
Only wait 6000 ms.

```
toastr.success(message, title, { timeOut: 6000 });
```

## after
Redirect '/' after wait 6000 ms.
Something like setTimeout.

```
toastr.success(message, title, { timeOut: 6000, redirectUrl: '/' });
```

**Comment by TimFerrell** [comment]
Toastr does not aim to support such functionality.
If you'd like to redirect your user after a period of time, please consider setTimeout.

**Comment by rnitame** [comment]
@TimFerrell I see. Thanks for support!
