### ISSUE TITLE
Improve build/test and submission instructions for v3

### ISSUE THREAD

**Issue by andrewtobin** [CodeSeven/toastr#466]
I am happy to work on this, but I figured it would be sensible to open an issue to submit against, and for opinions before doing so.

The build instructions have changed from v2 to v3, and some simple install/build/deploy instructions, or the beginnings of, could be useful for anyone looking to help.

**Comment by TimFerrell** [comment]
Sure, will do.

**Comment by TimFerrell** [comment]
Resolved via b93af2639cc322f64ad0f771e9d195ed01bdb3ff.
