### ISSUE TITLE
Bug: need to check if Toast has been closed #v3

### ISSUE THREAD

**Issue by andrewtobin** [CodeSeven/toastr#471]
In a couple of places in hideToast there are places where the toast may have been closed and no longer exists to be hidden.

One at the [beginning](https://github.com/CodeSeven/toastr/blob/v3/src/toastr.js#L523) as the result of a timeout expiring, and during the [animation callback](https://github.com/CodeSeven/toastr/blob/v3/src/toastr.js#L535).

It would be good to store the check if there is a timeout on the intervalId when [removing the toast](https://github.com/CodeSeven/toastr/blob/v3/src/toastr.js#L270) and clear any associated timeouts.

**Comment by TimFerrell** [comment]
Thanks!
