### ISSUE TITLE
toastr js and css minify blocked

### ISSUE THREAD

**Issue by harifetraram** [CodeSeven/toastr#488]
Hi, 

I have a problem, when i load my page, i have this error on the console "net::ERR_BLOCKED_BY_CLIENT" for toastr.min.js and toastr.min.css load.

When i disable my adblock, i don't have the error.

Can someone help me please?

**Comment by Boboss74** [comment]
I report the example here https://forums.lanik.us/viewtopic.php?f=91&t=34539

Hi, same here, but the moderator of the adblock FR list want a REAL example (i have only local sample or demo sample). Do you have a "real" online example please?

**Comment by TimFerrell** [comment]
This has been corrected by the AdBlock team. Thanks to those who assisted.
