### ISSUE TITLE
Toastr blocked by adblock

### ISSUE THREAD

**Issue by SnafuB** [CodeSeven/toastr#489]
Toastr is now blocked by all ad blockers ... That causes a javascript crash due to "toastr is not defined" error. Hope you'll soon find a solution! : /

**Comment by Boboss74** [comment]
I report the example here https://forums.lanik.us/viewtopic.php?f=91&t=34539

Hi, same here, but the moderator of the adblock FR list want a REAL example (i have only local sample or demo sample). Do you have a "real" online example please?

**Comment by Boboss74** [comment]
Deplicates of #488

**Comment by SnafuB** [comment]
Fixed by Adblock FR moderator

**Comment by TimFerrell** [comment]
Hey guys - can you please link me to the conversation with moderator? I would like to prevent this in the future.

**Comment by TimFerrell** [comment]
Thank you both for reporting the errant action to the moderator.
