### ISSUE TITLE
Text wrapping when word should be passed to a new line

### ISSUE THREAD

**Issue by craig-memero** [CodeSeven/toastr#491]
I am seeing some unexpected text wrapping behaviour. I could not see any setting on how to control this (I was expecting the wrapped word to be moved down to the next line only wrapping words that can't fit on a single line). Have I missed something or is this a bug?

![image](https://cloud.githubusercontent.com/assets/20622985/21283948/4ec394be-c448-11e6-9b7a-d3dd420ae642.png)

**Comment by TimFerrell** [comment]
Not sure why this is happening, but line break specifications are in CSS. 

Have you checked the CSS for the element to see what the value is?
