### ISSUE TITLE
cannot display "\n" as line break

### ISSUE THREAD

**Issue by wzdxy** [CodeSeven/toastr#496]
when I run `toastr.info("page1 \n page2")`, 
I wish it can show:

page1    
page2    

but now is:

page1 page2

**Comment by john-sanders-2** [comment]
\n is not a valid line break in HTML. Use <br>.

**Comment by ErroneousFatality** [comment]
What john-sanders-2 tried to write is: `<br>`

**Comment by john-sanders-2** [comment]
Yes, `<br>` is indeed what I meant to write. Thank you @ErroneousFatality

**Comment by kurtcarpenter** [comment]
May be able to use the CSS rule: `white-space: pre` or similar to render `\n` as newlines - not sure if maintainers want to force this behavior by default?

**Comment by grantiverson** [comment]
@TimFerrell Recommend closing because this was a user issue, not an issue with the library.
