### ISSUE TITLE
toastr not working

### ISSUE THREAD

**Issue by teerachel** [CodeSeven/toastr#501]
Hi, my toastr isn't working. I just shows the toastr but doesn't disappear. 

                if (!error) {
                    Command: toastr["success"]("Registration successful!")
                    toastr.options = {
                        "closeButton": false,
                        "debug": false,
                        "newestOnTop": false,
                        "progressBar": false,
                        "positionClass": "toast-top-right",
                        "preventDuplicates": false,
                        "onclick": null,
                        "showDuration": "300",
                        "hideDuration": "1000",
                        "timeOut": "5000",
                        "extendedTimeOut": "1000",
                        "showEasing": "swing",
                        "hideEasing": "linear",
                        "showMethod": "fadeIn",
                        "hideMethod": "fadeOut"
                    }
                    Router.go('/');
                } else {
                    console.log('error');
                }

Any idea what's up with it? 

I have put the <link> and <script> details in my html file.

**Comment by burtyish** [comment]
Hmmm not sure what you meant with `Command: toastr["success"]("Registration successful!")`. That doesn't look valid to me.

Try it like this:
```js
toastr.success("Registration successful!", {
                    closeButton: false,
                    debug: false,
                    // ... And the rest of your options
                }
```

**Comment by teerachel** [comment]
Thanks :)
