### ISSUE TITLE
include jquery 3 in support matrix

### ISSUE THREAD

**Issue by mcshaz** [CodeSeven/toastr#504]
the bower file lists the dependency as `"jquery": ">=1.6.3 <3"`

On quick looking and basic testing, I cannot see this library using anything deprecated in jquery 3.2. If not, and if testing passed, can the bower.json be adjusted accordingly?

Thanks.

**Comment by EikiProg** [comment]
I don't think that this will do with just an upgrade in the bower.json.

I got `TypeError: Cannot call a class as a function` when using it with jquery 3.2 normal or slim version and work fine with 2.2.4.

But it's sure would be great to have it compatible with jquery 3 for the slim version.
It's would meen to drop the compatibility with IE8 or not, I'm not aware of the change involved for the upgrade.

**Comment by duzun** [comment]
jQuery v3 is becoming the standard, so it is worth the upgrade.
In one of my projects, toastr is the only library that stops me from upgrading to jQUery v3.

**Comment by TimFerrell** [comment]
No longer an issue since this commit: https://github.com/johnpapa/toastr-bower/commit/113a6f6f995e39d965de3947edf8021ed2d5fda2
Thanks for reporting.
