### ISSUE TITLE
Conflict with Materializecss toaster

### ISSUE THREAD

**Issue by freddy-daniel** [CodeSeven/toastr#510]
Hi I'm using materializecss framework for my website, Now i want user toastr instead of Materialize.toast.
But toastr styles is not applied it is shown same as materializecss toast

**Comment by Kylegabriel** [comment]
where do i find the answer in here I have also the same problem. Please link thanks alot

**Comment by leodufer** [comment]
fix using class name toastr [https://github.com/CodeSeven/toastr/pull/543]( https://github.com/CodeSeven/toastr/pull/543)
