### ISSUE TITLE
will this add a xss config field

### ISSUE THREAD

**Issue by 21k** [CodeSeven/toastr#514]
normal times ,we add the content or the title without any more thought of their security. 
exactly,if use the content from the user's input ,it's terrible!

![qq 20170423231201](https://cloud.githubusercontent.com/assets/13778916/25314622/48f9c8fa-287a-11e7-91ea-131bb00593ed.png)

**Comment by 21k** [comment]
I find   that there is a options escapeHtml, while it is false default , so can it be true default?

**Comment by TimFerrell** [comment]
For backwards compatibility, it will not be true by default.

**Comment by ghost** [comment]
Hello,

Is there a development for this issue? I encountered the same problem during security tests.
