### ISSUE TITLE
Cannot read property 'extend' of undefined 

### ISSUE THREAD

**Issue by AnCze** [CodeSeven/toastr#516]
Hi, after npm install toastr --save, setup link and script in my [index.html](https://github.com/AnCze/AnCze.github.io/blob/292713e6dfbc34baae0c34ce8774a30c7cc2df69/src/index.html) and uncomment this <script>  toastr.success('test toastr')</script> on the bottom of it I have error like 
![image](https://cloud.githubusercontent.com/assets/24229704/25554692/058e952e-2cd4-11e7-8a6f-d70daa4b613c.png) 
Do you guys have idea why?

**Comment by ManojSethuraman** [comment]
Same issue here too :( , its getting created for me when i try to clear the toastr

**Comment by AnCze** [comment]
Hi, yes your right. I've made the same and toastr start working. Solved.

**Comment by tappu123** [comment]
Yes boss you are right. I did and Solved.

**Comment by hashmachine07** [comment]
Yup got resolved after JQuery import

**Comment by 2297028416** [comment]
i am try do it ,but it still not working,
