### ISSUE TITLE
Toastr does not change position if option positionClass is changed

### ISSUE THREAD

**Issue by rajmondburgaj** [CodeSeven/toastr#528]
I am having an issue with generating multiple toasters. I tried creating two toasters like below:

                        toastr.options = {
                            "closeButton": true,
                            "debug": true,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-bottom-left",
                            "preventDuplicates": false,
                            "onclick": null,
                            "showDuration": "0",
                            "hideDuration": "0",
                            "timeOut": "50000",
                            "extendedTimeOut": "3000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                                toastr["warning"]("You have successully added a new job!", "");
                        toastr.options = null;
                    
                    
                        toastr.options = {
                            "closeButton": true,
                            "debug": true,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-top-center",
                            "preventDuplicates": false,
                            "onclick": null,
                            "showDuration": "0",
                            "hideDuration": "0",
                            "timeOut": "50000",
                            "extendedTimeOut": "3000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                                toastr["success"]("You have successully added a new job!", "");
                        toastr.options = null;

I am expecting to see two toasters in two different position but they go with first position configuration.

Is that a bug or a behaviour that can be fixed somehow ?

**Comment by TimFerrell** [comment]
Toasts can only hold one position on the screen at a time due to the way the container for the toasts works. You'll notice that if you wait for the toast fired first to disappear, and then fire the next one, that the positions will be different.

**Comment by rajmondburgaj** [comment]
I know that but I thought it seemed to me more like a bug than a way how it works :(

**Comment by ferrugemjs** [comment]
Its a bug

**Comment by halimb** [comment]
this should be a bug...
