### ISSUE TITLE
toastr won't show immediately

### ISSUE THREAD

**Issue by Ssabin-devalore** [CodeSeven/toastr#530]
Hey,

I'm using toastr 2.1.2 with angularjs 1.4.8.
the toastr doesn't show up immediately when triggering it:
toastr.warnning('test')

only after a few times of triggering it shows up.
any idea why?

**Comment by TimFerrell** [comment]
What does your console show?

Tim Ferrell

**Comment by Ssabin-devalore** [comment]
No errors are shown

**Comment by Ssabin-devalore** [comment]
I found out that the toastr was appended to some svg body element and that was the reason i didn't see it.
Thanks anyway
