### ISSUE TITLE
jQuery dependency is not declared

### ISSUE THREAD

**Issue by QuentinRoy** [CodeSeven/toastr#535]
jQuery is a dependency of this library but is not declared in package.json.

As a result, the library does not work when installed with `npm`.

**Comment by TylorShin** [comment]
Temp way: I tried to install Jquery manually, then it's working now.

**Comment by QuentinRoy** [comment]
Of course you can still install it manually, but that's not how npm package are supposed to work!

**Comment by QuentinRoy** [comment]
Closing since this has been fixed in 3a450044394d4a4260fefbdb748d71bb304d66ea.
