### ISSUE TITLE
Toaster Error Icon Display Issue

### ISSUE THREAD

**Issue by adhip94** [CodeSeven/toastr#537]
![toasterissue](https://user-images.githubusercontent.com/20703483/29910109-3b84182e-8e46-11e7-86db-72a1f945daa2.png)

Any Reason why my toaster error icon is coming like this? 
I just updated from an old version of toastr to the latest one.

**Comment by ffocsi** [comment]
Looks like the error shield icon is mixed with a filled in warning icon.

The icons are base64 encoded pngs in the css file. Are you using some kind of custom toast-error class?

**Comment by adhip94** [comment]
Yes, looks like the inspinia template I was using contained custom css icons for the toaster.

Have fixed it now.
