### ISSUE TITLE
2.1.3 is not in npm

### ISSUE THREAD

**Issue by rmadamanchi** [CodeSeven/toastr#541]
http://registry.npmjs.com/toastr

Is there a plan to publish 2.1.3 to npm?

**Comment by burtyish** [comment]
Duplicate of #450

**Comment by pompex** [comment]
This project is so dead.

**Comment by xemasiv** [comment]
Any updates on this? Anyone maintaining a forked branch?

**Comment by Pysis868** [comment]
Almost missed the neat suggestions mentioned in #450, notably some `package.json` customizations, and some forks that GitHub would not report when I checked the Insights tab, Forks section, saying something about having a lot of networks to browse, so only reporting a portion of them, but then finding no results there...

It would be too bad if NPM really doesn't let you re-publish packages like that, but I don't know much about it.

**Comment by TimFerrell** [comment]
I just pushed `2.1.4`, which is the same as `2.1.3` except for the tag: https://www.npmjs.com/package/toastr
