### ISSUE TITLE
Toastr for express js

### ISSUE THREAD

**Issue by jaouadballat** [CodeSeven/toastr#548]
How can i use the package for my express js application

**Comment by mohanen** [comment]
Toastr runs in the client side (browser) , it doesn't matter which server side framework or language you use.

Include the cdn links or downloaded files in your head of html.
Just implement it in the html (including template engine files like ejs handle bars or pug) file or scripts. 

By the way i am also using it in express.

**Comment by TimFerrell** [comment]
Thanks for helping out, @mohanen . Sounds like this issue is closed.
