### ISSUE TITLE
$toastElement[options.showMethod] is not a function

### ISSUE THREAD

**Issue by hermione3690** [CodeSeven/toastr#561]
for some reason, I get the following error
`$toastElement[options.showMethod] is not a function at displayToast`
Googling brought me to issues [504](https://github.com/CodeSeven/toastr/issues/504) and [509](https://github.com/CodeSeven/toastr/issues/509) which both refer to toastr not working with the jquery version.
504 refers to a recent commit 
> No longer an issue since this commit: johnpapa/toastr-bower@113a6f6

But I still have the error showing up.
509 talks about downgrading the jquery version, which for me is no option I'm afraid.
Is there perhaps something else going on that I'm missing?
(running jquery 3.3.1 btw)

**Comment by hermione3690** [comment]
nvm, found the problem. I am using the slim version of jquery, which doesn't include the animations...

**Comment by thiensubs** [comment]
Yes. Exactly this problem will happen when using jquery.slim.
Please close this issue.
