### ISSUE TITLE
Scrolling within toastr message

### ISSUE THREAD

**Issue by shiggins8** [CodeSeven/toastr#563]
If I have a really long message to display inside of toastr (or a table with a lot of rows), is there any way to enable vertical scrolling? I've tried everything I can think of and can't seem to figure out how to prevent the scrolling from going to my webpage (instead of interacting with the message itself). Anyone had any luck with this?

**Comment by TimFerrell** [comment]
You can insert HTML into the content of the toast, so one idea would be to create a `div`, and allow that `div` to scroll.

**Comment by shiggins8** [comment]
I tried modifying the scrollability of my html content, however the toastr message itself still seems to ignore that and scrolls only affect the main page behind my toastr.

**Comment by TimFerrell** [comment]
By default toastr will pass through `pointer-events` to the underlying elements. It sounds like your scroll events are being ignored on the `div` and passed through to the element underneath. Check out https://css-tricks.com/almanac/properties/p/pointer-events/ . Most likely applying `pointer-events:auto` to your `div` will allow it scroll as you intended.

**Comment by shiggins8** [comment]
Thanks for the help! I couldn't get that working quite right but I found a suitable workaround without using the toastr methods.

**Comment by achilleus68** [comment]
> Thanks for the help! I couldn't get that working quite right but I found a suitable workaround without using the toastr methods.

Can you share your solution?

**Comment by antman3351** [comment]
Here's what a did to allow scrolling long messages ( like debug output )
```CSS
#toast-container .toast-message {
    overflow-y: auto;
    max-height: 95vh; /* Without limiting the height the scroll won't work */
}
```
