### ISSUE TITLE
Toaster Message Not Displaying Complete Content

### ISSUE THREAD

**Issue by SajjadGit** [CodeSeven/toastr#567]
Today i noticed one issue related to Toast message ,  if the message contains < then any word following the < is not showing under toaster message.

Ex:  SAJJAD<ALI 

then toaster will show only SAJJAD , its excluding <ALI 

I even tried this inside  http://codeseven.github.io/toastr/demo.html

**Comment by adarshmadrecha** [comment]
Seems like a bug to me. I would suggest using HTML character map `&gt;`

**Comment by TimFerrell** [comment]
@john-sanders-2 nailed it. If you want to escape HTML characters, refer to this documentation: https://github.com/CodeSeven/toastr#escape-html-characters
