### ISSUE TITLE
facing error in toastr css

### ISSUE THREAD

**Issue by mukeshkamboj1** [CodeSeven/toastr#577]
while using  //cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css  it's showing error  on 

var ss = doc.createElement("style"), css = styleBlocks[k].join("\n");
        ss.type = "text/css";
        ss.media = k;
        head.insertBefore(ss, lastLink.nextSibling);
        if (ss.styleSheet) {
            ss.styleSheet.cssText = css;

when value of k is print,not showing error on value of k=all, i don't understand , pls solve this issue

**Comment by TimFerrell** [comment]
I'm not sure, but I don't believe that this issue is specific to toastr. Closing, as it doesn't appear to be an issue specific to this library.

**Comment by mukeshkamboj1** [comment]
Hello sir,
  If i use timer tick event, then it create problem. like on page there are
2 timer,on one timer tick event i m performing another operation and on 2nd
timer tick event i m showing toaster message,then it create problem,may be
coz of time .
