### ISSUE TITLE
HTML breaklines not working even if escapeHTML option is enabled

### ISSUE THREAD

**Issue by sonsonixon** [CodeSeven/toastr#579]
HTML breaklines is not working in Toastr even is escapeHTML is true.

**Comment by adarshmadrecha** [comment]
@sonsonixon , can you share your code? Only then can someone comment on your issue.

**Comment by sonsonixon** [comment]
I enable HTMLEscape by ` toastr.option.escapeHTML: true`

I try inserting HTML line breaks in the toastr using `toastr.error("This is <br> a message", "Title", {timeOut: 5000});` but its not working.

**Comment by grantiverson** [comment]
@sonsonixon Did you try using `toastr.option.escapeHTML = true;` like it says in README? It worked for me this way https://codepen.io/grantiverson/pen/zLvROy.

@TimFerrell Recommend closing.

**Comment by TimFerrell** [comment]
Thanks for the recommendation, @grantiverson. Closing.
