### ISSUE TITLE
Updated to bootstrap v4.1.1; toastr stopped working.

### ISSUE THREAD

**Issue by tyler-shuhnicki** [CodeSeven/toastr#581]
The only relevant change to our project is an update to bootstrap to v4.1.1. Toastr messages are not displaying, and no errors are being printed to the console. 

Has anyone experienced this?

**Comment by Tsyklop** [comment]
Look in your custom styles if it exist. I tried this on clear bootstrap 4.1 and all fine.

**Comment by tyler-shuhnicki** [comment]
Update: Thanks for the lead. Turns out it wasn't anything to do with bootstrap, but a new version of our template (step of web). Thanks!
