### ISSUE TITLE
Obvious question: what is the purpose of toastr?

### ISSUE THREAD

**Issue by RubixRevenge** [CodeSeven/toastr#590]
It may seem like a stupid question, but there's a reason for asking this. 

I came across this package because it was briefly mentioned in a Pluralsight course. I saw it _briefly_ used when the Pluralsight author was doing a think-aloud while developing a jQuery script and showing how to control DOM event bubbling. The toastr notifications were a convenient way to see that elements were triggered.

Is toastr something that is intended to assist in jQuery development? Is it meant for production? Is it a tool that is meant for anything and anywhere? Just trying to understand the purpose of this tool so that I can set some good learning habits for this tool.

**Comment by john-sanders-2** [comment]
We use it in our production e-commerce website, for in-page notifications. The site doesn't use Bootstrap, so we needed a small, lightweight alert tool. It works great for our limited use cases.
