### ISSUE TITLE
Execution of script in message

### ISSUE THREAD

**Issue by vvnsk** [CodeSeven/toastr#629]
Steps to Reproduce:
Send javascript in message

Expected Result:
javascript code should be considered as string

Actual Result:
Code is being executed.

![image](https://user-images.githubusercontent.com/14221153/66864731-6a89f800-ef5b-11e9-9915-e4092907dc72.png)

**Comment by vvnsk** [comment]
Please accept the PR to fix the below issue https://github.com/CodeSeven/toastr/pull/523/commits/3e70ccf9d50c4b578caaf059c7538fa9b0ec8802

**Comment by TexasSwede** [comment]
It is up to you as developer to santize the data you are sending to a plugin/function. Since you are the one creating the application, you should clean any data before you pass it on.

**Comment by vvnsk** [comment]
Agreed, Although i feel the necessity to educate the developers to sanitize, By mentioning the same in Read me, or handling the same in the plugin/function. 
The issue is a potential threat to cross site scripting and I don't want developers using the Plugin to figure out the same the hard way.

**Comment by snoopysecurity** [comment]
Hey @vvnsk I think there is already an option to escape HTML (https://github.com/CodeSeven/toastr#escape-html-characters) did you try this?

**Comment by vvnsk** [comment]
@snoopysecurity I haven't tried that, but that seems to be the solution to my concern. Thank you very much!
