### ISSUE TITLE
Fail to install - Cannot read property

### ISSUE THREAD

**Issue by Cookiewookie87** [CodeSeven/toastr#633]
I have followed this quick instal guide (i have added to folder toastr.css and toastr.js:

1. Link to toastr.css <link href="toastr.css" rel="stylesheet"/>
2. Link to toastr.js <script src="toastr.js"></script>
3. use toastr to display a toast for info, success, warning or error
// Display an info toast with no title
toastr.info('Are you the 6 fingered man?')

and then I got an error:
Cannot read property 'extend' of undefined
    at getOptions (toastr.js:452)
    at Object.info (toastr.js:71)
    at HTMLButtonElement.testClick (script.js:25)

Now I do not know how to solve this or use it (beginner here)

**Comment by Cookiewookie87** [comment]
Got it, jQuery must be added

**Comment by neilyoung** [comment]
jquery is not mentioned as dependency and I'm asking myself, why is it required?
