### ISSUE TITLE
Unique Id for Indeterminate Toast

### ISSUE THREAD

**Issue by TorreyGarland** [CodeSeven/toastr#636]
Is there a way to uniquely identify an interdeterminate toast?

I have a potentially long running Ajax operation and I want to be able to close specific toasts, similar to the way that gritter does.

**Comment by EstesE** [comment]
Add this to the notify function in toastr.js:

> function setID() {
>&nbsp;&nbsp;&nbsp;&nbsp;if (options.id)$toastElement.attr('id', options.id);
> }
> 

Then add the setID to the personalizeToast function in toastr.js:

> function personalizeToast() {
> &nbsp;&nbsp;&nbsp;&nbsp;setIcon();
>&nbsp;&nbsp;&nbsp;&nbsp;setTitle();
>&nbsp;&nbsp;&nbsp;&nbsp;setMessage();
>&nbsp;&nbsp;&nbsp;&nbsp;setCloseButton();
>&nbsp;&nbsp;&nbsp;&nbsp;setProgressBar();
>&nbsp;&nbsp;&nbsp;&nbsp;setRTL();
>&nbsp;&nbsp;&nbsp;&nbsp;setID();
>&nbsp;&nbsp;&nbsp;&nbsp;setSequence();
>&nbsp;&nbsp;&nbsp;&nbsp;setAria();
> }
> 

Then pass an id in the options:

> toastr.options.id = guidFor({});
> toastr.info('Have fun storming the castle!', 'Miracle Max Says');
