### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by JeffryGonzalez** [CodeSeven/toastr#64]
From nuget, I install into a fresh MVC 3 project jQuery 1.9.1, then toastr 1.2.1 using the nuget package manager.

The following html file: 

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8"/>
    <link href="Content/toastr.css" rel="stylesheet" type="text/css" />
    <script src="Scripts/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="Scripts/toastr.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            toastr.options = { debug: true };
            toastr.info("Hello? Is This thing on?");
            toastr.success("Anything");
            toastr.error("Nada.");
        });
    </script>
</head>
<body>

</body>
</html>
```

shows nothing in Google Chrome v 25.0.1364.97 m nor IE 9 on Windows 7.

If I uninstall toastr 1.2.1 and Install-Package toastr -Version 1.1.4.2 it works just dandy.

With 1.2.1 I get nothing - the debug messages print, but don't seem to contain anything useful.

Thanks!

**Comment by Kylegabriel** [comment]
Im using Materialiceszz Framework And I use Toastr but its not rendering properly in materialiceszz but when i try in bootstrap its okay. I think theres a conflict in materiaclieszz toaster dialog and toastr
.. help me
