### ISSUE TITLE
Add import without links necessity

### ISSUE THREAD

**Issue by guilhermedjr** [CodeSeven/toastr#671]
Is there a way to use toastr (in React apps, for example) without needing to add css and js links in html, just doing imports? I'm really missing this possibility, and I think it's super necessary for other people too.

If this possibility exists, it would be good to see it on the documentation.

**Comment by Frenzoid** [comment]
There is a [npm package](https://www.npmjs.com/package/toastr) that i haven't tried yet.

From the docs i'd say, you'll have to add on your app.js the following (I haven't tried it, im just following intuition):

```
import 'toastr';
```

Yet for the css.. unless you use sass or similar, there doesn't seem to be any raw css file to import from the npm package.
![image](https://user-images.githubusercontent.com/30338644/129111924-fea22093-f514-4997-9b42-7c26c92fae5b.png)

**Comment by guilhermedjr** [comment]
Hi, sorry for the delay, I just saw your comment now. :)

In my case, the React app didn't have an App.js file, I was working with "modules". But after some more testing I found that yes, it is possible to use imports, directly in the component files.

![toast1](https://user-images.githubusercontent.com/44452846/139703895-369fde25-7112-4b91-911f-52b27e7e7697.PNG)

**Comment by AdnanHussainTurki** [comment]
Just to have @guilhermedjr answer in raw text:

`import * as toastr from 'toastr'`
`import 'toastr/build/toastr.min.css';`
