### ISSUE TITLE
toastr does not work with bootstrap 5 ?

### ISSUE THREAD

**Issue by avnermosh** [CodeSeven/toastr#697]
Should I expect toastr to work properly with bootstrap 5 ? See my post in: 
https://stackoverflow.com/questions/75242712/toastr-options-not-working-with-bootstrap-5

**Comment by theveloperspl** [comment]
you can close this issue as it was all your mistake

**Comment by avnermosh** [comment]
This is not an issue. It was my mistake.
I didn't notice the clear() command which cleared the toasts and led me to believe that the Library was not working ok.
