### ISSUE TITLE
Add option: Block user interface

### ISSUE THREAD

**Issue by renatoeufe** [CodeSeven/toastr#74]
:+1:

**Comment by vladimiry** [comment]
> Its for alerts
Actually classic browser alerts blocks user input, ie has modal view mode, but "toastr" hasn't such mode.

**Comment by TimFerrell** [comment]
Toastr will never intentionally block the ui thread.

**Comment by vladimiry** [comment]
I meant not blocking ui thread (actually there is no separate ui thread, javascript is single threaded), but modal mode. Ok never will, got it. But I don't understand why toastr's tooltips/alers must not has "modal" mode (ie on top of entire page gray DIV).

**Comment by saitolabs** [comment]
@vladimiry +1

**Comment by gpashis** [comment]
@vladimiry 👍 
This is really nice option to have. Sometimes it is helpful when we depend on user input before accepting any other action.
