### ISSUE TITLE
Callback function on click of sticky notification.

### ISSUE THREAD

**Issue by aravindtga** [CodeSeven/toastr#76]
I am using toastr to show notification...I want to call a function to update some details when the notification is closed(i.e clicked on the notification)..Is there any way to do it with toastr.

**Comment by xelpmocShubham** [comment]
Great plugin!!.

**Comment by bjorn-ali-goransson** [comment]
For the record, one should just be able to:

    var x = toastr.info(...);
    $(x.el).click(function(){ ... });

**Comment by JeremyLopez** [comment]
@bjorn-ali-goransson it didn't work for me with `$(x.el).click(function(){ ... });`.  I needed to use `$(x).click(function(){ ... });`
