### ISSUE TITLE
Group toasts by type

### ISSUE THREAD

**Issue by saitolabs** [CodeSeven/toastr#78]
I noticed that at certain times the user finds it difficult to read a sequence of notifications, because they disappear quickly.

I suggest an option to group the toast by type (success, info, warning, error) showing the number of notifications that have the same type.

and then, when you dismiss a toast, the toast that is "behind" is displayed and the number of notifications decreased.

**Comment by TimFerrell** [comment]
Keeping on roadmap for a potential v3 candidate.
